Dokploy/dokploy

docker/prod.sh

On GCP instances lsof -i gives false positive about port usage. Using ss -tulnp fixes this.
Before installation:
```bash
root@vm-instance-7ed850b:/home/ewert# curl -sSL https://dokploy.com/install.sh | sh
Error: something is already running on port 80
root@vm-instance-7ed850b:/home/ewert# curl localhost
curl: (7) Failed to connect to localhost port 80 after 0 ms: Connection refused
root@vm-instance-7ed850b:/home/ewert# curl 127.0.0.1
curl: (7) Failed to connect to 127.0.0.1 port 80 after 0 ms: Connection refused
root@vm-instance-7ed850b:/home/ewert# lsof -i :80
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
google_os 514 root    3u  IPv4  17711      0t0  TCP vm-instance-7ed850b.europe-west3-b.c.hres-sandbox.internal:36796->metadata.google.internal:http (ESTABLISHED)
google_gu …
```

feat: use `ss -tulnp | grep ':PORT '` instead of `lsof -i :PORT`

---

.github/workflows/pull-request.yml
docker/build.sh
docker/push.sh
next.config.mjs
package.json
pnpm-lock.yaml

Updating build, so it gets build for arm64 aarch64 and the normal x86, using buildx automatically pushing the new images to the registry [see docs here](https://docs.docker.com/reference/cli/docker/buildx/build/#push)
Nothing else needs to change as docker automatically selects the correct version to pull in prod.sh
Closes #35 #33 #41

feat: Update build.sh to provide arm64, aarch64 and x86 images

---

components/dashboard/postgres/general/show-external-postgres-credentials.tsx

Postgres external url currently returns password:password when it should be user:password.

Correct Postgres url from password:password to user:password

---

pages/api/deploy/[refreshToken].ts

Tracking issue #107 
Added an filter when `application.sourceType` is equal `docker`. 
- User setup docker image **WITHOUT** including tag, then
-> nothing changes, application still listening to dockerhub events from webhook and adding deploy action to queue.
- User setup docker image **INCLUDING** tag, then
- Extract tag from provided image
- Extract tag from webhook payload
-> If not equals 
- ends with 301, do not add it on queue
Fixes #107 
Resolves #107

feat: (#107) webhook listener filter docker events based on image tag.

---

.gitignore
components/dashboard/mariadb/general/show-external-mariadb-credentials.tsx
components/dashboard/mariadb/general/show-internal-mariadb-credentials.tsx
components/dashboard/mongo/general/show-external-mongo-credentials.tsx
components/dashboard/mongo/general/show-internal-mongo-credentials.tsx
components/dashboard/mysql/general/show-external-mysql-credentials.tsx
components/dashboard/mysql/general/show-internal-mysql-credentials.tsx
components/dashboard/postgres/general/show-external-postgres-credentials.tsx
components/dashboard/postgres/general/show-internal-postgres-credentials.tsx
components/dashboard/redis/general/show-external-redis-credentials.tsx
components/dashboard/redis/general/show-internal-redis-credentials.tsx
components/shared/toggle-visibility-input.tsx

In the current Version inside the Database Detail Views, the Password is exposed inside the internal connectionstrings.
I have updated the Detailviews to replace the passwords inside the connectionstrings with '*' so the password doesn't get accidentally leaked :)
I have also updated this for the external connectionstring, when exposing the database to the internet where this is even more critical

Updated the database view to hide the password in the connection string

---

components/dashboard/application/advanced/traefik/show-traefik-config.tsx

There was a minor spelling error on traefik card description

[Docs/style]: Fix minor spelling error

---

components/dashboard/project/add-application.tsx
components/dashboard/project/add-compose.tsx
components/dashboard/project/add-database.tsx

The current error message for naming validation in AppName should be updated to explicitly state that only lowercase letters are supported. The new error message should be clear and concise, applying to naming **applications**, **databases**, and **compose items**.

Clarify error message for naming validation in `AppName`

---

components/dashboard/compose/monitoring/show.tsx

It is the same as https://github.com/Dokploy/dokploy/pull/257 but for monitoring:
Current: 
Update:

fix: docker compose monitoring

---

templates/appsmith/docker-compose.yml
templates/directus/docker-compose.yml
templates/listmonk/docker-compose.yml
templates/odoo/docker-compose.yml
templates/plausible/docker-compose.yml

This PR updates the path of certain template which use the filesystem of dokploy to define volumes, which was causing in each deploy the volumes and everything delete so we move to `/files` folder

fix(templates): change path of volumes to be in files folder to prevent the volumes delete in each deploy

---

README.md

Fixes the alt name for both supafort.com and steamsets.com

chore: update readme.md with alt names

---

apps/dokploy/__test__/traefik/server/update-server-config.test.ts
apps/dokploy/server/utils/traefik/web-server.ts

Fix entry point name mismatch in configs
- config (/etc/dokploy/traefik/traefik.yml) uses 'websecure'
- config (/etc/dokploy/traefik/dynamic/dokploy.yml) was using 'web-secure'
Updated app config to use 'websecure', fixing Web Domain Setup for Dokploy panel.

fix: align entry point names in configs

---

apps/dokploy/__test__/traefik/traefik.test.ts
apps/dokploy/components/dashboard/application/build/show.tsx
apps/dokploy/components/dashboard/application/general/generic/save-docker-provider.tsx
apps/dokploy/drizzle/0029_colossal_zodiak.sql
apps/dokploy/drizzle/meta/0029_snapshot.json
apps/dokploy/drizzle/meta/_journal.json
apps/dokploy/server/api/routers/application.ts
apps/dokploy/server/db/schema/application.ts
apps/dokploy/server/utils/builders/docker-file.ts
apps/dokploy/server/utils/filesystem/directory.ts

Close #284 
Context: some users reported when they were trying to build a dockerfile the docker context can vary depending on the needs for example:
1.  when using a normal application
2.  when using monorepo
3. When managing multiple applications in the same project 
which can be difficult to predict the entry point and also can be more beneficial in terms of security because the context path gives access to all files on the system from the specified path, so specifying the context can be useful for certain specific cases the default will be where the dockerfile is specified.

fix(docker-context): add docker context path #284

---

apps/dokploy/components/dashboard/application/advanced/traefik/show-traefik-config.tsx
apps/dokploy/components/dashboard/application/advanced/traefik/update-traefik-config.tsx
apps/dokploy/components/dashboard/file-system/show-traefik-file.tsx
apps/dokploy/components/dashboard/project/add-template.tsx
apps/dokploy/components/dashboard/settings/web-server/show-main-traefik-config.tsx
apps/dokploy/components/dashboard/settings/web-server/show-server-traefik-config.tsx
apps/dokploy/components/shared/code-editor.tsx
apps/dokploy/package.json
pnpm-lock.yaml

Hi, I fixed two small UI issues. 
1. The template dialog does not disappear after selecting the template. I think the user will continue to complete the deployment of the selected service after clicking Deploy button, so the model dialog should be closed. 
2. The config file editor of traefik does not wrap, causing the editor to extend width infinitely, I added line wrap to fix it.

fix(ui): close dialog after templete selected & add config editor line wrapping

---

apps/dokploy/server/utils/docker/utils.ts

When trying to clear unused volumes from the settings page it only removes "anonymous volumes" not all unused volumes.
We need to run "docker volume prune --all" to remove all unused volumes.
Ref: https://docs.docker.com/reference/cli/docker/volume/prune/#:~:text=-a%2C%20--all,just%20anonymous%20ones

refactor(cleanUpUnusedVolumes): Remove all unused volumes, not just anonymous ones

---

apps/dokploy/public/templates/typebot.svg
apps/dokploy/templates/templates.ts
apps/dokploy/templates/typebot/docker-compose.yml
apps/dokploy/templates/typebot/index.ts

This Pull Request adds a new template for **Typebot** with the necessary configuration to enable email-based login. The main changes include:
- Creation of the `docker-compose.yml` file for Typebot, which includes services for PostgreSQL, the Typebot builder and the Typebot viewer.
- Configuration of required environment variables for Typebot's operation, such as `SMTP` variables.
Please note that to fully enable email login functionality, you must configure an SMTP server. While a basic option is included in the `docker-compose.yml` for local testing, it is recommended to use a more robust external SMTP service for production environments.

feat: add Typebot template with email login configuration.

---

apps/dokploy/templates/umami/docker-compose.yml

There is a bug in the old version that crashes on the web. 
I would propose the version to be set as postgresql-latest, but I understand why a certain version is set in apps.

fix: umami version

---

apps/dokploy/components/dashboard/project/add-template.tsx

After refactoring the project directory in v0.5.1 the wrong path to the template source code was used, this change fixes the path

fix: invalid template source path

---

apps/dokploy/components/dashboard/application/advanced/redirects/add-redirect.tsx
apps/dokploy/components/dashboard/application/domains/add-domain.tsx
apps/dokploy/components/dashboard/compose/domains/add-domain.tsx

This PR is for #333 , I simply added into the add-redirect modal a select with 2 presets for www and non-www redirect. After selection the fields will auto-fill with the preset values.
Also added a little refactor that improve keyboard navigation on the two add-domain modals by putting the certificate select after the https switch field.

#333 add flexible www/non-www redirect option

---

apps/dokploy/components/dashboard/application/advanced/ports/update-port.tsx
apps/dokploy/components/dashboard/application/domains/add-domain.tsx
apps/dokploy/components/dashboard/compose/domains/add-domain.tsx
apps/dokploy/components/ui/input.tsx

I have encapsulated a `NumberInput` component to handle string inputs with simple processing of number type fields(eg `port`).
If needed, I can implement the `NumberInput` component in a two-stage approach: during input and upon input completion. This is typically used for handling situations with floats.
| Before                                                                 | After                                                                  |
|------------------------------------------------------------------------|------------------------------------------------------------------------|
| ![Kapture 2024-09-30 at 16 05 42](https://github.com/user-attachments/assets/3739f5c3-db55-486e-9071-64886d88c5f5) | ![Kapture 2024-09-30 at 16 32 …

Fix port input value becoming NaN

---

apps/docs/content/docs/core/templates/overview.mdx
apps/docs/mdx-components.tsx
apps/dokploy/public/templates/roundcube.svg
apps/dokploy/templates/roundcube/docker-compose.yml
apps/dokploy/templates/roundcube/index.ts
apps/dokploy/templates/templates.ts

Based off https://github.com/Dokploy/dokploy/pull/458 I'd like to also add a template for roundcube so it's easier to get a self-hosted email solution up and running.
Please keep in mind some VPS/ISP block port 25.

feat: add roundcube template

---

apps/dokploy/package.json

It sounds like we’re running into an issue with` tsx --watch` flag causing unnecessary reloads, particularly when working with the _apps/dokploy/server_ folder.
The `tsx --watch` flag is commonly used to watch TypeScript files and automatically recompile/restart the application when files are changed. However, in our case, since Next.js is already handling the auto-reload for the server, it might be redundant and leading to performance issues.
For other cases, a manual restart is enough.

fix: tsx watch flag unwanted reload

---

apps/dokploy/server/api/routers/application.ts

The endpoint to create an application/service executes successfully but it doesn't return any values.
https://docs.dokploy.com/en/docs/api/reference-api/reference-application#application-create
This makes it hard to develop as we don't know the ID of the application we just created and looks weird as all the other endpoints return values.
Adding that return statement makes the return of create the same as get one application
https://docs.dokploy.com/en/docs/api/reference-api/reference-application#application-one
Example without fix:
Example with fix:
Making sure the output marches get one:

fix: Application create endpoint returns value

---

README.md

Adds the missing organization to the readme under the correct tier

Add missing organization to readme

---

apps/website/components/Hero.tsx

Fixes the logo alignment on the website to go from this:
to this:

fix(website): improve sponsor logo alignment

---

apps/dokploy/pages/index.tsx

This commit updates the URL for the "Lost your password?" link in the user interface. The change replaces the previous URL with the correct link to the password reset documentation.
Changes made:
- Updated the `href` attribute of the Link component
- Ensured the link points to the correct documentation page for resetting passwords
This fix improves user experience by directing users to the proper resource for password recovery.

fix: update reset password link URL

---

apps/docs/content/docs/core/get-started/manual-installation.cn.mdx
apps/docs/content/docs/core/get-started/manual-installation.mdx
apps/website/public/canary.sh
apps/website/public/feature.sh
apps/website/public/install.sh
packages/server/src/services/auth.ts

Adds support for custom ENV to the installation for `ADVERTISE_ADDR` which allows to set any IP and this will be injected to the installation to initialize the docker swarm on that IP, if no value is provided, the Public IP will be used.

feat(dokploy): add env for ADVERTISE_ADDR to installation #593

---

apps/dokploy/components/dashboard/application/advanced/ports/update-port.tsx

This PR fix an issue where the target port field was accepting a string instead of a number.

fix(dokploy): Wrong input for `target port` when updating ports.

---

apps/dokploy/pages/index.tsx

Fixed a broken link to password reset documentation.
I changed the link of *Lost your password?* from: https://docs.dokploy.com/docs/core/get-started/reset-password
to https://docs.dokploy.com/docs/core/reset-password.

fix(signin-page): fix a broken link to password reset docs

---

README.md
apps/dokploy/components/dashboard/settings/profile/profile-form.tsx
apps/dokploy/lib/utils.ts
apps/dokploy/pages/dashboard/settings/appearance.tsx

feat(Profile): support use Gravatar as avatar

---

apps/dokploy/templates/stirling/docker-compose.yml

Fixing the issue with stirling when trying to deploy.
In this merge request I am just transposing the docker compose example from [Stirling documentation](https://docs.stirlingpdf.com/Getting%20started/Installation/Docker/Docker%20Install).
#742 
Before : :-1: 
After : :+1:

fix: stirling docker compose

---

apps/dokploy/components/dashboard/settings/destination/add-destination.tsx
apps/dokploy/components/dashboard/settings/destination/constants.ts
apps/dokploy/components/dashboard/settings/destination/update-destination.tsx
apps/dokploy/components/dashboard/settings/web-server/update-server.tsx
apps/dokploy/drizzle/0045_smiling_blur.sql
apps/dokploy/drizzle/meta/0045_snapshot.json
apps/dokploy/drizzle/meta/_journal.json
apps/dokploy/server/api/routers/destination.ts
apps/dokploy/templates/templates.ts
packages/server/src/db/schema/destination.ts
packages/server/src/utils/backups/utils.ts

**Introducing an Optional 'Provider' Attribute**
- Introduced a new optional 'Provider' attribute to S3 Destinations configuration.
- Allows users to specify custom providers for S3 interactions.
- Enhances flexibility in managing external storage providers.
Issues where custom S3 configurations, such as Alibaba Cloud OSS, were not functioning have been resolved.

feat: add optional Provider attribute to S3 Destinations

---

apps/dokploy/components/dashboard/application/delete-application.tsx
apps/dokploy/components/dashboard/compose/delete-compose.tsx
apps/dokploy/components/dashboard/mariadb/delete-mariadb.tsx
apps/dokploy/components/dashboard/mongo/delete-mongo.tsx
apps/dokploy/components/dashboard/mysql/delete-mysql.tsx
apps/dokploy/components/dashboard/postgres/delete-postgres.tsx
apps/dokploy/components/dashboard/redis/delete-redis.tsx

Now, we ask the user to enter the project name and the app/database/compose name (my-super-project/postgres-database-silly-245) to delete an app/database/compose to avoid handling errors during navigation.
https://github.com/user-attachments/assets/e7bfc172-6c0f-475d-9d36-595dcba5b3b9

feat: Add an input box to enter the project name for a second confirmation when deleting the application.

---

apps/dokploy/components/dashboard/projects/project-enviroment.tsx
apps/dokploy/components/dashboard/projects/show.tsx
apps/dokploy/components/dashboard/settings/servers/show-servers.tsx
apps/dokploy/pages/dashboard/project/[projectId].tsx

refactor: apply suggested changes

---

apps/dokploy/components/dashboard/application/general/generic/save-bitbucket-provider.tsx
apps/dokploy/components/dashboard/application/general/generic/save-github-provider.tsx
apps/dokploy/components/dashboard/application/general/generic/save-gitlab-provider.tsx
apps/dokploy/components/dashboard/compose/general/generic/save-bitbucket-provider-compose.tsx
apps/dokploy/components/dashboard/compose/general/generic/save-github-provider-compose.tsx
apps/dokploy/components/dashboard/compose/general/generic/save-gitlab-provider-compose.tsx
apps/dokploy/components/dashboard/database/backups/add-backup.tsx
apps/dokploy/components/dashboard/database/backups/update-backup.tsx
apps/dokploy/components/dashboard/mysql/volumes/show-volumes.tsx
apps/dokploy/components/dashboard/project/add-template.tsx
apps/dokploy/components/dashboard/settings/billing/show-billing.tsx
apps/dokploy/components/dashboard/settings/cluster/registry/show-registry.tsx
apps/dokploy/components/dashboard/settings/notifications/add-notification.tsx
apps/dokploy/components/dashboard/settings/notifications/update-notification.tsx
apps/dokploy/components/dashboard/settings/servers/show-servers.tsx
apps/dokploy/components/ui/input-otp.tsx
apps/dokploy/pages/api/deploy/github.ts
apps/dokploy/styles/globals.css
lefthook.yml
package.json
pnpm-lock.yaml

fix: add missing server flag boolean

---

apps/dokploy/components/dashboard/requests/columns.tsx

Added the RequestAddr in the table, before, you had to click on a row to see it, and it was more complicated to read, whereas now you can analyse requests more easily.

style: add RequestAddr in the requests table

---

apps/dokploy/server/api/routers/notification.ts
packages/server/src/utils/notifications/build-error.ts
packages/server/src/utils/notifications/build-success.ts
packages/server/src/utils/notifications/database-backup.ts
packages/server/src/utils/notifications/docker-cleanup.ts
packages/server/src/utils/notifications/dokploy-restart.ts

Now, discord notifications are easier to read and to understand, here are a few examples

style: improved discord webhooks notifications style

---

apps/dokploy/components/dashboard/settings/git/github/add-github-provider.tsx
apps/dokploy/templates/templates.ts

Added the ability to easy check if you already have an app installed as there are no way to sync or delete apps directly from Dokploy. Dynamicly updates the link when user selected organization.

feat: improve github app validation

---

packages/server/src/utils/notifications/build-error.ts
packages/server/src/utils/notifications/build-success.ts
packages/server/src/utils/notifications/database-backup.ts
packages/server/src/utils/notifications/docker-cleanup.ts
packages/server/src/utils/notifications/dokploy-restart.ts

This adds Discord's own timestamp format, which ensures that the timestamp is localised according to the user's timezone.

feat(dynamic timestamp): add dynamic discord timestamps

---

apps/dokploy/components/dashboard/docker/config/show-container-config.tsx
apps/dokploy/components/shared/code-editor.tsx

This PR enhances the Docker View Config view by using the shared Code Editor component. This improvement makes container configurations more readable and consistent with other editor experiences in Dokploy.

feat(docker): use code editor when displaying container config

---

apps/dokploy/components/layouts/dashboard-layout.tsx
apps/dokploy/pages/dashboard/project/[projectId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/application/[applicationId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/compose/[composeId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/mariadb/[mariadbId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/mongo/[mongoId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/mysql/[mysqlId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/postgres/[postgresId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/redis/[redisId].tsx
apps/dokploy/pages/dashboard/settings/appearance.tsx
apps/dokploy/pages/dashboard/settings/billing.tsx
apps/dokploy/pages/dashboard/settings/certificates.tsx
apps/dokploy/pages/dashboard/settings/cluster.tsx
apps/dokploy/pages/dashboard/settings/destinations.tsx
apps/dokploy/pages/dashboard/settings/git-providers.tsx
apps/dokploy/pages/dashboard/settings/notifications.tsx
apps/dokploy/pages/dashboard/settings/profile.tsx
apps/dokploy/pages/dashboard/settings/registry.tsx
apps/dokploy/pages/dashboard/settings/server.tsx
apps/dokploy/pages/dashboard/settings/servers.tsx
apps/dokploy/pages/dashboard/settings/ssh-keys.tsx
apps/dokploy/pages/dashboard/settings/users.tsx

Adding Titles to the pages.
Format is: 
{pageName} | Dokploy for main and settings pages
Project {projectName} | Dokploy for Projects
Project {projectName} | {appName} | Dokploy for services/applications
Feel free to comment if you agree with the naming "convention" or want sth else :)

feat: add page titles

---

apps/dokploy/components/dashboard/application/delete-application.tsx
apps/dokploy/components/dashboard/compose/delete-compose.tsx
apps/dokploy/components/dashboard/mariadb/delete-mariadb.tsx
apps/dokploy/components/dashboard/mongo/delete-mongo.tsx
apps/dokploy/components/dashboard/mysql/delete-mysql.tsx
apps/dokploy/components/dashboard/postgres/delete-postgres.tsx
apps/dokploy/components/dashboard/redis/delete-redis.tsx

This PR makes the resource name a clickable badge so it can be quickly copied to the clipboard for pasting.

feat(delete): add quick copy to resource to clipboard in delete modal

---

apps/dokploy/components/dashboard/application/deployments/show-deployment.tsx
apps/dokploy/components/dashboard/compose/deployments/show-deployment-compose.tsx
apps/dokploy/components/dashboard/docker/logs/docker-logs-id.tsx
apps/dokploy/components/dashboard/docker/logs/line-count-filter.tsx
apps/dokploy/components/dashboard/docker/logs/since-logs-filter.tsx
apps/dokploy/components/dashboard/docker/logs/status-logs-filter.tsx
apps/dokploy/components/dashboard/docker/logs/terminal-line.tsx
apps/dokploy/components/dashboard/docker/logs/utils.ts
apps/dokploy/components/ui/badge.tsx

feat(logs): multi select fiter logs & hide/show timestamp

---

apps/dokploy/components/dashboard/settings/cluster/nodes/show-node-data.tsx

This PR uses the Code Editor to display the Node Config similar to #865

feat(cluster): use code editor for node config

---

apps/dokploy/components/ui/secrets.tsx

fix(preview-deployments): wrap long envs

---

apps/dokploy/components/dashboard/settings/notifications/delete-notification.tsx
apps/dokploy/components/dashboard/settings/notifications/show-notifications.tsx
apps/dokploy/components/dashboard/settings/notifications/update-notification.tsx

style(notifications): better notification item style

---

apps/dokploy/components/dashboard/settings/web-server/toggle-auto-check-updates.tsx
apps/dokploy/components/dashboard/settings/web-server/update-server.tsx
apps/dokploy/components/dashboard/settings/web-server/update-webserver.tsx
apps/dokploy/components/layouts/navbar.tsx
apps/dokploy/server/api/routers/settings.ts
packages/server/src/services/settings.ts

- added toggle in Settings->Server->Updates dialog for automatic server update checking (enabled by default, saved in local storage)
- use interval (15min) to periodically check for new updates (if enabled via toggle)
- check for new updates on page load (if enabled via toggle)
- show "Update available" button in header when new server update is available
- improved logic for checking available updates to use Docker hub API instead of pulling image, which makes checking update a lot faster
- moved pulling latest release to `updateServer` action
- removed green dot pinging while server is updating
- added button loading text while server is updating
- added automatic page reload on successful server update
- added information about page reload in confirmation modal and success toast
- …

feat: automatic check for updates

---

apps/dokploy/components/dashboard/settings/web-server/toggle-auto-check-updates.tsx
apps/dokploy/components/dashboard/settings/web-server/update-server.tsx
apps/dokploy/components/dashboard/settings/web-server/update-webserver.tsx
apps/dokploy/components/layouts/navbar.tsx
apps/dokploy/server/api/routers/settings.ts
packages/server/src/services/settings.ts

UI enhancements based on #951.

New Updates UI

---

apps/dokploy/components/dashboard/docker/logs/terminal-line.tsx
apps/dokploy/components/dashboard/docker/logs/utils.ts
apps/dokploy/package.json
apps/dokploy/tailwind.config.ts
pnpm-lock.yaml

This pull request focuses on enhancing the log parsing and highlighting functionality by integrating the `fancy-ansi` library and removing redundant code. Additionally, it updates the dependencies and configuration files accordingly.
* [`apps/dokploy/components/dashboard/docker/logs/terminal-line.tsx`](diffhunk://#diff-219a675bf21dd72a836467a41488fb5c123d565c76981e5397529b1730eca434R10-R22): Integrated `fancy-ansi` to replace the custom ANSI parsing logic, simplifying the code and improving performance. [[1]](diffhunk://#diff-219a675bf21dd72a836467a41488fb5c123d565c76981e5397529b1730eca434R10-R22) [[2]](diffhunk://#diff-219a675bf21dd72a836467a41488fb5c123d565c76981e5397529b1730eca434L37-L67)
* [`apps/dokploy/components/dashboard/docker/logs/utils.ts`](diffhunk://#diff-fa0f53f954dd05e0ea1a4 …

feat(logs): use fancy-ansi for ansi colors

---

apps/dokploy/components/dashboard/docker/terminal/docker-terminal-modal.tsx
apps/dokploy/components/dashboard/settings/web-server/docker-terminal-modal.tsx

This PR fixes the issue where pressing the Escape key in terminal modals triggers an unwanted exit confirmation. The fix:
1. Adds `onEscapeKeyDown` handler to prevent default behavior in both docker terminal modal components
2. Maintains consistent behavior with the existing web server terminal modal
3. Prevents accidental terminal closures while maintaining the explicit confirmation dialog
Changes:
- Added escape key prevention to main terminal dialog in both docker terminal modals
- Added escape key prevention to confirmation dialogs
- Follows the pattern from the working terminal-modal.tsx implementation
**Made by Devin**

fix: prevent Esc key from closing terminal modals

---

packages/server/src/db/schema/utils.ts
packages/server/src/services/application.ts
packages/server/src/services/compose.ts
packages/server/src/services/deployment.ts
packages/server/src/services/mariadb.ts
packages/server/src/services/mongo.ts
packages/server/src/services/mysql.ts
packages/server/src/services/postgres.ts
packages/server/src/services/preview-deployment.ts
packages/server/src/services/redis.ts

This PR is meant to improve and fix the handling of app names particularly in create and update APIs. It rids of spaces from the input JSON and replaces them with `-`.
**Reasoning**
In the UI, spaces are not allowed when inputting the app name but its not the same using the API as it inserts it as is. 
This resulted to a bug I encountered when trying to deploy a compose service. The deployment failed due to an unknown command error as Dokploy tries to execute this command which is obviously invalid:
```bash
║ App Name: hello world
║ Build Compose 🐳
║ Detected: 0 mounts 📂
║ Command: docker compose -p hello world -f docker-compose.yml up -d
║ --build --remove-orphans
║ Source Type: docker raw ✅
║ Compose Type: docker-compose ✅
...
unknown docker command: "compose hello"
```

fix: fixed/improved handling of app names in api

---

packages/server/src/setup/server-setup.ts
packages/server/src/setup/traefik-setup.ts

This pull request includes updates to the `server-setup.ts` and `traefik-setup.ts` files to make the Traefik configuration more dynamic by utilizing environment variables for version and port numbers.
* [`packages/server/src/setup/server-setup.ts`](diffhunk://#diff-6c5bd715fb2bd5b9e487e44796de9dbdc6baecaf657016b1331d5000d5813d0dR12-R14): Added `TRAEFIK_SSL_PORT`, `TRAEFIK_PORT`, and `TRAEFIK_VERSION` imports from `traefik-setup` to dynamically set these values.
* [`packages/server/src/setup/server-setup.ts`](diffhunk://#diff-6c5bd715fb2bd5b9e487e44796de9dbdc6baecaf657016b1331d5000d5813d0dL513-R516): Modified the `createTraefikInstance` function to use the `TRAEFIK_VERSION` environment variable instead of a hardcoded version.
* [`packages/server/src/setup/server-setup.ts`](diffhunk://#diff- …

fix(setup): use traefik port/version from env

---

apps/dokploy/components/dashboard/application/preview-deployments/show-preview-builds.tsx
apps/dokploy/components/dashboard/application/preview-deployments/show-preview-deployments.tsx
apps/dokploy/components/dashboard/application/preview-deployments/show-preview-settings.tsx

This pull request includes several changes to the `apps/dokploy` components, focusing on enhancing the user interface and improving functionality. The most important changes involve adding new icons, updating the display of preview deployments, and modifying button triggers.
* [`apps/dokploy/components/dashboard/application/preview-deployments/show-preview-deployments.tsx`](diffhunk://#diff-4505cc9d42cfc577ce5d6b7cf17d0fbab51c44b1289f93609a67230ef311fbaeL91-R214): Updated the display of preview deployments with new UI elements, including status indicators, better layout for deployment details, and improved interaction elements.
* [`apps/dokploy/components/dashboard/application/preview-deployments/show-preview-builds.tsx`](diffhunk://#diff-85a2108d79c13ab563f308f1a8763c129d3b660f30b987c09fb …

feat(preview-deployments): new UI

---

packages/server/src/utils/builders/compose.ts

This pull request includes a change to improve error logging in the `compose.ts` utility file. The change ensures that error messages are more descriptive by including the error message in the log output. Resolves #975.
* [`packages/server/src/utils/builders/compose.ts`](diffhunk://#diff-f9cc68879adf21866cfd9c3f794ccc2c914313263081bab55b29c6156f6faf05L71-R71): Modified the error logging to include the error message in the log output.

fix: show error message when compose builder throws

---

apps/dokploy/components/dashboard/application/domains/add-domain.tsx
apps/dokploy/components/dashboard/application/preview-deployments/add-preview-domain.tsx
apps/dokploy/components/dashboard/application/preview-deployments/show-preview-settings.tsx
apps/dokploy/components/dashboard/compose/domains/add-domain.tsx
apps/dokploy/components/dashboard/project/add-application.tsx
apps/dokploy/components/dashboard/project/add-compose.tsx
apps/dokploy/components/dashboard/project/add-database.tsx
apps/dokploy/components/dashboard/settings/certificates/add-certificate.tsx
apps/dokploy/public/locales/en/settings.json
packages/server/src/constants/index.ts

This pull request includes several changes to improve the clarity and functionality of the domain and certificate management components in the `dokploy` application. The most important change is refactoring path handling in the server constants to expose the certificate to a path accessible by the traefik container.
Label and placeholder updates:
* [`apps/dokploy/components/dashboard/application/domains/add-domain.tsx`](diffhunk://#diff-1782ff28942283ea9707889fe9cf7a8829b33ce1b1a487a36ca78012beaba915L267-R281): Updated `FormLabel` and `SelectValue` placeholders to "Certificate Provider" and "Select a certificate provider" respectively, and changed "Letsencrypt" to "Let's Encrypt".
* [`apps/dokploy/components/dashboard/application/preview-deployments/add-preview-domain.tsx`](diffhunk://#dif …

fix(certificates): ensure certificates are accessible by traefik

---

apps/dokploy/components/dashboard/application/deployments/show-deployment.tsx
apps/dokploy/components/dashboard/project/add-database.tsx
apps/dokploy/components/dashboard/settings/cluster/registry/add-docker-registry.tsx
apps/dokploy/components/dashboard/settings/web-server/manage-traefik-ports.tsx

This PR aims to stop the browser from autofilling some inputs where it is not expected that the currently saved credentials of the user should be submitted.
I only added this to the inputs where I noticed this myself, but I see there are more inputs this could potentially be added to.

fix: turn off `autoComplete` for some inputs

---

apps/dokploy/components/dashboard/application/logs/show.tsx
apps/dokploy/components/dashboard/compose/logs/show-stack.tsx
apps/dokploy/components/dashboard/compose/logs/show.tsx
apps/dokploy/server/wss/docker-container-logs.ts
packages/server/src/services/docker.ts

This pull request includes several changes to enhance the display of Docker container states using badges and to improve the Docker logs functionality across different components. The most important changes include the addition of a badge state color function, the integration of badges in multiple components, and updates to Docker logs handling.
Enhancements to Docker container state display:
* [`apps/dokploy/components/dashboard/application/logs/show.tsx`](diffhunk://#diff-25fdc6c638e3b4409aacc3b69471700d09acfd05b2e97d4ab60ce912220d5badR1): Added `badgeStateColor` function to determine badge color based on container state and integrated `Badge` component to display container states. [[1]](diffhunk://#diff-25fdc6c638e3b4409aacc3b69471700d09acfd05b2e97d4ab60ce912220d5badR1) …

Feat: simplify node service log & add badge color on list service/container

---

apps/dokploy/components/dashboard/settings/servers/show-swarm-overview-modal.tsx
apps/dokploy/components/dashboard/swarm/details/details-card.tsx
apps/dokploy/components/dashboard/swarm/monitoring-card.tsx
apps/dokploy/pages/dashboard/swarm.tsx

feat: swarm overview style

---

apps/dokploy/pages/dashboard/project/[projectId].tsx

fix: inconsistent service card height

---

apps/dokploy/styles/globals.css

Fixed the horizontal layout shifting that occurs when you navigate between a page with and a page without scrollbar.

feat: prevent layout shifting from scrollbar

---

apps/dokploy/pages/index.tsx

I had an issue signing in to my dashboard only to find out it was because the first letter of my email was in caps.

convert email to lower case when loging in

---

apps/dokploy/components/dashboard/settings/servers/actions/show-dokploy-actions.tsx
apps/dokploy/components/dashboard/settings/servers/add-server.tsx
apps/dokploy/components/dashboard/settings/servers/show-servers.tsx
apps/dokploy/components/dashboard/settings/servers/update-server.tsx
apps/dokploy/components/dashboard/settings/web-server/local-server-config.tsx
apps/dokploy/components/dashboard/settings/web-server/terminal-modal.tsx
apps/dokploy/components/dashboard/settings/web-server/terminal.tsx
apps/dokploy/pages/dashboard/settings/servers.tsx
apps/dokploy/public/locales/en/settings.json
apps/dokploy/public/locales/pl/settings.json
apps/dokploy/server/wss/terminal.ts
apps/dokploy/server/wss/utils.ts

- added status logs before connection is made in terminal
- added enter the terminal feature to Settings -> Server -> Server dropdown
- added some common terminal texts to translations (en/pl)
- added expandable local server config in terminal modal with settings for port and username, saved in local storage
- added rerender of terminal on local config save
- modified terminal WSS to allow local server connections, with automatic generation of SSH key and authorized_keys if they don't exist (uses `auto_generated-dokploy-local` key name to not collide with others)
- added constant terminal container height to avoid jumping when terminal loads for the first time

feat: local server terminal access

---

apps/dokploy/components/auth/login-2fa.tsx

The Input has been centered on the card and the border made gray-700 to ensure if is better visible on dark background

style(2fa): make pin input centered and make boarder more white to make it more visible

---

apps/dokploy/components/dashboard/settings/web-server/update-server.tsx
apps/dokploy/components/dashboard/settings/web-server/update-webserver.tsx
apps/dokploy/components/layouts/navbar.tsx
apps/dokploy/pages/api/health.ts
apps/dokploy/server/api/routers/settings.ts

- added /api/health endpoint for frontend app
- changed docker service restart command not to be awaited during server update
- navbar will now open the updates modal (with version information, releases link, etc.) intead of directly asking for confirmation of update
- refactored updates modal to allow using `updateData` which is already fetched
- updated confirm update modal to inform that using the panel is not possible during update
- updated confirm update modal to not allow closing the modal, and inform about update being done
- fixed checking if server update finished by using health endpoint instead of waiting for docker service restart command which doesn't properly finish due to restart of the whole app causing an error to be thrown instead
- removed ping icon from "new version …

feat: use check updates modal for update available in navbar

---

packages/server/src/setup/server-setup.ts

The installation script for rclone requires unzip to be present in order to install. This adds this dep to the deps installed as it's not present on Debian.

fix: added unzip to server setup

---

CONTRIBUTING.md

1. See:
https://github.com/Dokploy/dokploy/blob/332416b7e7d9ceb740dc67a22302e74deb9f1205/CONTRIBUTING.md?plain=1#L171-L185
`generateBase64` is being used at line 183 without being imported from `"../utils"`
2. `mountPath` no longer exists - it is now `filePath` I presume:
https://github.com/Dokploy/dokploy/blob/332416b7e7d9ceb740dc67a22302e74deb9f1205/apps/dokploy/templates/utils/index.ts#L20-L21

docs(contribution): fix template index.ts

---

Dockerfile
apps/dokploy/server/utils/docker.ts
apps/dokploy/server/wss/terminal.ts
apps/dokploy/server/wss/utils.ts

- added `iproute2 ` to dependecies in Dockerfile (required for `ip route` command)
- added util for checking if Dokploy is running in WSL
- added util for getting Docker host IP
- added command to allow access for local server terminal, which is displayed in the terminal when connection fails, after auto-generating private SSH key. This command must be run on the server manually by the user and is required only once to append the auto-generated SSH key to `authorized_keys` file on the server. Also added similar command for granting permission access to the `/etc/dokploy/ssh` directory when needed.
- fixed the local server terminal connection host to use Docker host IP instead of localhost in production env
- refactored error message for client authentication to be separated for local …

fix: connection to local server terminal

---

packages/server/src/utils/notifications/build-success.ts

Remove "> " when decoration is turned off.

fix(notifications): discord decoration tiny adjustment

---

apps/dokploy/components/dashboard/settings/servers/show-servers.tsx

Fixes #1097
Reverts this: https://github.com/Dokploy/dokploy/pull/1084#discussion_r1912683332

fix: query for ssh keys to show servers, rather than default empty

---

apps/dokploy/components/layouts/side.tsx
apps/dokploy/components/ui/sidebar.tsx

Improve sidebar animation by applying ease-out and transitioning the logo button.
https://github.com/user-attachments/assets/1e587558-50fe-4a6b-8fd4-f7914e1a7e57

refactor(sidebar): improve animation

---

apps/dokploy/server/utils/docker.ts

- added missing await before `isWSL()` check, which caused it to always return `true` and picking `host.docker.internal` even on linux not running on WSL

fix: isWSL check was not awaited

---

apps/dokploy/components/dashboard/docker/show/show-containers.tsx
apps/dokploy/components/dashboard/file-system/show-traefik-system.tsx
apps/dokploy/components/dashboard/monitoring/web-server/show.tsx
apps/dokploy/components/dashboard/projects/show.tsx
apps/dokploy/components/dashboard/swarm/monitoring-card.tsx
apps/dokploy/components/layouts/side.tsx
apps/dokploy/pages/dashboard/settings/profile.tsx
apps/dokploy/pages/dashboard/settings/server.tsx

This pull request includes various formatting and layout adjustments across multiple components to improve consistency and readability. The most important changes are grouped by theme below.
* [`apps/dokploy/components/dashboard/docker/show/show-containers.tsx`](diffhunk://#diff-8e9aca544b3cdafc4dc26d31755a9af2da438efab7f73679a4f46141754827b9L56-R56): Updated the formatting of state initialization and method calls in `ShowContainers` component. [[1]](diffhunk://#diff-8e9aca544b3cdafc4dc26d31755a9af2da438efab7f73679a4f46141754827b9L56-R56) [[2]](diffhunk://#diff-8e9aca544b3cdafc4dc26d31755a9af2da438efab7f73679a4f46141754827b9L166-R166) [[3]](diffhunk://#diff-8e9aca544b3cdafc4dc26d31755a9af2da438efab7f73679a4f46141754827b9L185-R185)
* …

fix(style): clean up sidebar related style issue

---

apps/dokploy/components/dashboard/database/backups/show-backups.tsx

This pull request updates the link text and destination in the database backup settings prompt to align with recent frontend UI changes introduced by the Dokploy redesign. The change ensures that users are directed to the correct page for configuring backup providers.
- The link in the prompt advising users to set up a backup provider has been updated:
- **Old destination and text (pre-Dokploy redesign):**
- Link Text: `Settings`
- Link Destination: `/dashboard/settings/server`
- **New destination and text (aligned with the Dokploy redesign):**
- Link Text: `S3 Destinations`
- Link Destination: `/dashboard/settings/destinations`
- Recent **frontend UI changes by Dokploy** restructured the settings page, which made the old link (`/dashboard/settings/server`) outdated and irrelevant for …

fix: Update link text and destination for db backup settings

---

apps/dokploy/components/dashboard/settings/users/add-permissions.tsx
apps/dokploy/server/api/routers/project.ts
packages/server/src/db/schema/user.ts
packages/server/src/services/user.ts

This PR fixes the typo "accesed" -> "accessed" in TS files - specifically:
- accessedProjects
- accessedServices
I've left the mapping to DB untouched (unsure how Dokploy handles migrations in version upgrades atm).
---
As an aside, I was discovered this while attempting to implement the "custom sort order" services for projects and services (suggested in #700). It appears that a user's access to projects and services are stored as string arrays instead of in dedicated permission tables:
https://github.com/Dokploy/dokploy/blob/332416b7e7d9ceb740dc67a22302e74deb9f1205/packages/server/src/db/schema/user.ts#L43-L50
which makes it difficult to implement a custom sort order on a per-user basis.
Would you be open to receiving a PR that normalises the schema + changes the way user permissions …

chore: typo "accesed" changed to "accessed" for TS code

---

apps/dokploy/components/dashboard/application/advanced/volumes/show-volumes.tsx

Shows `filePath` instead of `mountPath` for file mounts (mount path appears to be empty?)
---
Before (mount path is undefined):
After (mount path is visible):

fix(ui): volume mountPath undefined for file mount - meant to display filePath instead?

---

apps/dokploy/components/dashboard/application/advanced/volumes/show-volumes.tsx

As suggested by @190km in this [comment](https://github.com/Dokploy/dokploy/pull/1160#issuecomment-2604783414), this PR
- limits the volume file mount content to **max 10 lines**
- preserve white spaces
---
Before:
After:

fix(ui): volume file mount content, line clamp and preserve whitespace

---

apps/dokploy/components/dashboard/project/add-template.tsx

I've noticed that the spacing in the "add Template"  Card-Footer is incosistent, so I fixed it.
The card on the right is the new appearance :)

style: fix incosistent spacing in Card-Footer

---

apps/dokploy/components/dashboard/projects/show.tsx
apps/dokploy/components/dashboard/settings/ssh-keys/handle-ssh-keys.tsx

- Reimplement domain dropdown from previous codebase
- Implement scrollable dropdown with max height for better UX
https://github.com/user-attachments/assets/722b74c7-a6fb-4512-b6b4-77f8cfe2558f
- add download functionality for SSH keys

feat: restore domain dropdown menu functionality

---

apps/dokploy/components/layouts/side.tsx

Hi, @Siumauricio . 
Thank you for the approval of my PR earlier (#1165 and #1166). However, it turns out that I missed one more handling, that is for the `UpdateServerButton` component which is still visible for normal user when an update is available.
My assumption is that this button should be visible for admin only. So if that's currect, in this mini follow up PR, I'd like to add a small improvement to handle this as a follow up.
Thank you for your great works! Been enjoying using Dokploy so far and I'm happy that I can contribute to the project :)

fix(ui): add condition to show update server button to admin only

---

apps/dokploy/pages/api/deploy/github.ts

fix: Multiple Preview Deployments

---

apps/dokploy/templates/superset/docker-compose.yml
apps/dokploy/templates/superset/index.ts

Renamed `db` to `superset_postgres` and `redis` to `superset_redis`.
This is to avoid potential hostname conflicts with other compose/applications that may use the name `redis` or `db` hostname on `dokploy-network`.

fix(template): prepend superset_ to postgres/redis

---

apps/dokploy/templates/listmonk/docker-compose.yml
apps/dokploy/templates/listmonk/index.ts

- Upgrade listmonk version to v4.
- Upgrade postgres version to 17-alpine (according to [listmonks docker-compose](https://github.com/knadh/listmonk/blob/master/docker-compose.yml) file)
- Remove automatic admin credentials generation (because in version 4 there's an initial setup page)

feat: upgrade listmonk version

---

apps/dokploy/components/dashboard/projects/project-environment.tsx

The sentence "Use this syntax to reference project-level variables in your service environments" is duplicated in the dialog description and the callout. This removes the one in the description.

chore: remove duplicated sentence in projects dialog

---

apps/dokploy/components/dashboard/application/domains/show-domains.tsx
apps/dokploy/components/dashboard/compose/domains/show-domains.tsx

Fixes #1248 
- Made domain text white to match other clickable elements
- Enhanced text truncation and responsive layout
- Replaced Button components with semantic <span> elements for static information (ports/protocols)
- Improved hover states for better interaction feedback
These changes address usability friction points observed with new users. The improvements align the domains page with common platform patterns and Dokploy's existing UI conventions.
- Tested across different screen sizes
- Verified text truncation with long domain names
- Confirmed hover states and click interactions
- Checked accessibility with semantic markup changes
Let me know if you'd like any adjustments!

fix: improve domains page UX and button placement consistency

---

packages/server/src/utils/docker/domain.ts

Dokploy handle Traefik labels the same way for Docker Compose and Docker Stack projects but it makes Stack projects are unable to be exposed (or the user needs to manually add the labels).

fix: expose docker stack services

---

apps/dokploy/templates/pocketbase/docker-compose.yml

Reverts Dokploy/dokploy#1259
As [kucherenko](https://github.com/kucherenko) said, [0.25.0](https://hub.docker.com/r/spectado/pocketbase/tags) version does not exist.

revert "feat<templates>: Updated PocketBase version to 0.25.0" #1259

---

apps/dokploy/templates/templates.ts

Version mismatch: The WordPress template version was updated to v6.7.1 but not reflected in the templates.ts file.

chore: update wordpress version to v6.7.1

---

apps/dokploy/templates/superset/docker-compose.yml

As noted in https://github.com/Dokploy/dokploy/pull/1276#issuecomment-2655974236.
Similar to `superset`, we may want to document this for `metabase` and `grafana` as well, now that #1276 has been merged and these data analytics services are no longer on `dokploy-network`.

docs(template): note on networking for superset

---

apps/dokploy/templates/templates.ts
apps/dokploy/templates/umami/docker-compose.yml

Works fine on my self-hosted Dokploy instance!

chore: update umami to v2.16.1

---

apps/dokploy/components/layouts/side.tsx

Before this PR, the spacing between sidebar items was inconsistent across sections:
This PR fixes that!

fix: make spacing between sidebar elements consistent

---

apps/dokploy/components/layouts/user-nav.tsx

When clicking the user account button at the bottom of the left sidebar
- `Profile` is **missing** from the self-host version
- `Profile` is the second-from-top item in the cloud version
Given that everything is already accessible from the left sidebar with Dokploy's new UI, the most intuitive item that people would look for when clicking the user photo is `Profile`, and hence it should be first, i.e:
For comparison, here is GitHub:
This is, however, quite subjective, although I think at the least, `Profile` should be available in the self-host version's dropdown menu.

feat(ui): move profile to top of account dropdown

---

packages/server/src/utils/providers/bitbucket.ts

Fixes: https://github.com/Dokploy/dokploy/issues/1397
This change fetches 100 branches instead of the default 10 from Bitbucket.
**Before**
**After**

feat: Bitbucket branch length

---

CONTRIBUTING.md
Dockerfile
apps/dokploy/components/dashboard/application/build/show.tsx
apps/dokploy/components/dashboard/settings/servers/validate-server.tsx
apps/dokploy/drizzle/0069_legal_bill_hollister.sql
apps/dokploy/drizzle/meta/0069_snapshot.json
apps/dokploy/drizzle/meta/_journal.json
apps/dokploy/server/api/routers/server.ts
packages/server/src/db/schema/application.ts
packages/server/src/setup/server-setup.ts
packages/server/src/setup/server-validate.ts
packages/server/src/utils/builders/index.ts
packages/server/src/utils/builders/railpack.ts

- Introduce Railpack as a new build method for applications
- Update database schema to include 'railpack' in buildType enum
- Add Railpack installation and validation scripts for servers
- Implement Railpack build and command generation utilities
- Update UI to include Railpack as a build option with a 'New' badge
#1401

feat(application): add Railpack as a new build type

---

packages/server/src/utils/providers/gitlab.ts

- Change repository filtering to use 'user' kind instead of 'member'
- Add console logging for debugging GitLab provider and repository connection
- Ensure consistent filtering logic in both getGitlabRepositories and testGitlabConnection

fix(gitlab): update repository filtering and connection testing

---

apps/dokploy/components/dashboard/project/add-template.tsx
apps/dokploy/components/layouts/side.tsx
apps/dokploy/components/shared/breadcrumb-sidebar.tsx

Better breadcrumbs UX:
- Removed duplicate for single pages;
- Removed ending separator;
Before / After
Fixed text in template > server hint:

fix: breadcrumbs UX

---

apps/dokploy/components/dashboard/monitoring/free/container/show-free-container-monitoring.tsx

Removes the third shadow around the "monitoring" page content.
**Before:**
**After:**

refactor: remove unnecessary extra shadow from monitoring page

---

apps/dokploy/pages/dashboard/project/[projectId]/services/application/[applicationId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/compose/[composeId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/mariadb/[mariadbId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/mongo/[mongoId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/mysql/[mysqlId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/postgres/[postgresId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/redis/[redisId].tsx

Fixes #1261
Restructure the project view tabs to follow a more intuitive user journey:
Group tabs into "Initial Setup", "Deployment", and "Monitoring" sections
Maintain "Advanced" as a standalone option
Order tabs to match typical project workflow (configuration → deployment → monitoring)
**Why this change:**
This reorganization reduces cognitive load by grouping related functions, minimizes tab switching during common tasks, and provides a clearer mental model of the platform's workflow for new users.

feat: reorganize project view tabs into logical workflow groups #1261

---

apps/dokploy/components/dashboard/shared/rebuild-database.tsx
apps/dokploy/components/dashboard/shared/show-database-advanced-settings.tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/mariadb/[mariadbId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/mongo/[mongoId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/mysql/[mysqlId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/postgres/[postgresId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/redis/[redisId].tsx
apps/dokploy/server/api/routers/mariadb.ts
apps/dokploy/server/api/routers/mongo.ts
apps/dokploy/server/api/routers/mysql.ts
apps/dokploy/server/api/routers/postgres.ts
apps/dokploy/server/api/routers/redis.ts
packages/server/src/db/schema/mariadb.ts
packages/server/src/db/schema/mongo.ts
packages/server/src/db/schema/mysql.ts
packages/server/src/db/schema/postgres.ts
packages/server/src/db/schema/redis.ts
packages/server/src/index.ts
packages/server/src/utils/databases/rebuild.ts

- Implement RebuildDatabase component for all database types
- Create ShowDatabaseAdvancedSettings component to consolidate advanced settings
- Add rebuild API endpoints for Postgres, MySQL, MariaDB, MongoDB, and Redis
- Implement server-side database rebuild utility with volume and service removal
- Enhance database management with a dangerous zone for complete database reset

feat(databases): add database rebuild functionality

---

apps/dokploy/__test__/compose/domain/labels.test.ts
apps/dokploy/__test__/drop/drop.test.test.ts
apps/dokploy/__test__/traefik/traefik.test.ts
apps/dokploy/components/dashboard/application/domains/add-domain.tsx
apps/dokploy/components/dashboard/application/preview-deployments/add-preview-domain.tsx
apps/dokploy/components/dashboard/application/preview-deployments/show-preview-settings.tsx
apps/dokploy/components/dashboard/compose/domains/add-domain.tsx
apps/dokploy/components/dashboard/settings/web-domain.tsx
apps/dokploy/components/shared/code-editor.tsx
apps/dokploy/drizzle/0072_green_susan_delgado.sql
apps/dokploy/drizzle/0073_hot_domino.sql
apps/dokploy/drizzle/0074_black_quasar.sql
apps/dokploy/drizzle/meta/0072_snapshot.json
apps/dokploy/drizzle/meta/0073_snapshot.json
apps/dokploy/drizzle/meta/0074_snapshot.json
apps/dokploy/drizzle/meta/_journal.json
apps/dokploy/server/db/validations/domain.ts
packages/server/src/db/schema/application.ts
packages/server/src/db/schema/domain.ts
packages/server/src/db/schema/shared.ts
packages/server/src/db/validations/domain.ts
packages/server/src/services/preview-deployment.ts
packages/server/src/utils/docker/domain.ts
packages/server/src/utils/traefik/domain.ts

- Extend domain configuration to support custom certificate resolvers
- Add new "custom" certificate type option in domain forms
- Update database schema and validation to include custom certificate resolver
- Implement custom certificate resolver handling in Traefik and Docker domain configurations
- Enhance domain management with more flexible SSL/TLS certificate options

feat(domains): add custom certificate resolver support

---

apps/dokploy/__test__/drop/drop.test.test.ts
apps/dokploy/__test__/traefik/traefik.test.ts
apps/dokploy/components/dashboard/application/general/generic/save-bitbucket-provider.tsx
apps/dokploy/components/dashboard/application/general/generic/save-git-provider.tsx
apps/dokploy/components/dashboard/application/general/generic/save-github-provider.tsx
apps/dokploy/components/dashboard/application/general/generic/save-gitlab-provider.tsx
apps/dokploy/components/dashboard/compose/general/generic/save-bitbucket-provider-compose.tsx
apps/dokploy/components/dashboard/compose/general/generic/save-git-provider-compose.tsx
apps/dokploy/components/dashboard/compose/general/generic/save-github-provider-compose.tsx
apps/dokploy/components/dashboard/compose/general/generic/save-gitlab-provider-compose.tsx
apps/dokploy/drizzle/0075_young_typhoid_mary.sql
apps/dokploy/drizzle/0076_young_sharon_ventura.sql
apps/dokploy/drizzle/meta/0075_snapshot.json
apps/dokploy/drizzle/meta/0076_snapshot.json
apps/dokploy/drizzle/meta/_journal.json
apps/dokploy/package.json
apps/dokploy/pages/api/deploy/[refreshToken].ts
apps/dokploy/pages/api/deploy/compose/[refreshToken].ts
apps/dokploy/pages/api/deploy/github.ts
apps/dokploy/server/api/routers/application.ts
apps/dokploy/server/api/routers/settings.ts
packages/server/package.json
packages/server/src/db/schema/application.ts
packages/server/src/db/schema/compose.ts
packages/server/src/index.ts
packages/server/src/utils/watch-paths/should-deploy.ts
pnpm-lock.yaml

- Implement watch paths feature for GitHub and GitLab applications and compose services
- Add ability to specify paths that trigger deployments when changed
- Update database schemas to support watch paths
- Integrate micromatch for flexible path matching
- Enhance deployment triggers with granular file change detection
#1386 #873

feat(applications): add watch paths for selective deployments

---

packages/server/src/utils/databases/mariadb.ts
packages/server/src/utils/databases/mongo.ts
packages/server/src/utils/databases/mysql.ts
packages/server/src/utils/databases/postgres.ts
packages/server/src/utils/databases/redis.ts

All started when I tried to setup a mysql database backup to a S3 destination. I ran the manual backup and what I found on S3 was an empty sql file even though Dokploy said that it was a succesful dump. 
So, I decided to write my own script to do it. While doing it i discovered something quite interesting. When trying to do a mysqldump with wrong credentials it sitll creates the dump file but empty! Aha so something had to be wrong with my mysql credentials on my dokploy service.
I remembered that my root password ended in a whitespace. Could this mess with the dump command? Well, since the password it's written within quotes in the code then it works perfectly:
`"mysqldump --default-character-set=utf8mb4 -u 'root' --password='${databaseRootPassword}' --single-transaction --no-tablespaces …

Database empty backups fix

---

apps/dokploy/components/dashboard/application/general/generic/save-docker-provider.tsx
apps/dokploy/components/dashboard/project/add-database.tsx
apps/dokploy/components/dashboard/settings/cluster/registry/handle-registry.tsx

Better autocomplete work. Prevents browsers from automatically filling in Username and Password fields.
Use one-time-code instead of off value. [reference](https://developer.mozilla.org/en-US/docs/Web/Security/Practical_implementation_guides/Turning_off_form_autocompletion#managing_autofill_for_login_fields)
Tested for Chrome and Chromium based browsers.
Before / After

fix(ui): Autocomplete

---

apps/dokploy/components/dashboard/projects/show.tsx

Currently, long domains result in weird overflows:
This PR will truncate the values as shown below:
Users can always hover their mouse over each item to see the full URL displayed by their browser (e.g. bottom-left corner for FF).

fix: truncate domain overflow for external links

---

apps/dokploy/package.json
apps/dokploy/server/api/routers/compose.ts
packages/server/src/templates/index.ts

Change references from `compose.project.name` to `compose.appName` when processing compose templates to ensure correct project naming

refactor: update project name reference in compose template processing

---

apps/dokploy/__test__/templates/config.template.test.ts
packages/server/src/templates/processors.ts

Add support for processing environment variables defined as an array in template configurations, allowing more flexible env var definitions with direct string values and variable interpolation

feat(templates): support array-based environment variable configuration

---

apps/dokploy/components/layouts/side.tsx

Minor styling fix. Currently, the space between the navbar and actual content has a gap on the Projects page. Because the Projects page has a different structure than the other pages, it causes an inconsistency in the spacing.
I've tested with the pages I could find using this layout, but you may want to double-check that it doesn't break anything.

style: remove inconsistent gap between header and content

---

apps/dokploy/components/dashboard/application/update-application.tsx
apps/dokploy/components/dashboard/compose/update-compose.tsx
apps/dokploy/components/dashboard/mariadb/update-mariadb.tsx
apps/dokploy/components/dashboard/mongo/update-mongo.tsx
apps/dokploy/components/dashboard/monitoring/free/container/show-free-container-monitoring.tsx
apps/dokploy/components/dashboard/mysql/update-mysql.tsx
apps/dokploy/components/dashboard/postgres/update-postgres.tsx
apps/dokploy/components/dashboard/projects/handle-project.tsx
apps/dokploy/components/dashboard/redis/update-redis.tsx
apps/dokploy/components/dashboard/settings/web-server/docker-terminal-modal.tsx
apps/dokploy/components/dashboard/settings/web-server/show-modal-logs.tsx
apps/dokploy/public/locales/en/settings.json
apps/dokploy/server/api/routers/compose.ts

This pull request includes several improvements:
* Moved the `projectName` assignment to before the `generate` call in `compose.ts` to ensure project name is properly slugified.
* Updated placeholder text from "Tesla" to "Vandelay Industries" in multiple form components including `UpdateApplication`, `UpdateCompose`, `UpdateMariadb`, `UpdateMongo`, `UpdateMysql`, `UpdatePostgres`, `HandleProject`, and `UpdateRedis`. [[1]](diffhunk://#diff-b014793f5d52bb74d37c521e5b6cfe5831e032c64872c7481001ffd077c56fb4L124-R124) [[2]](diffhunk://#diff-046793df509de5c61ad827f0fdcf917ad8bc96d20031def0e021ebc0967d907cL124-R124) [[3]](diffhunk://#diff-ddf4043fb244e858e23d668aafcb7c5292557374515ad2101bc3aa26bc5f16fbL122-R122) [[4]](diffhunk://#diff-34bb0d7ab785de0f5a6ed847a8786d3ca63253246038677e667cda5fa2daa2b …

Various Improvements

---

apps/dokploy/components/dashboard/monitoring/free/container/show-free-container-monitoring.tsx

There is a duplicate "%" unit label on the CPU Usage monitoring graph:
Removes the duplicate label

fix: removed duplicate percentage label

---

packages/server/src/utils/docker/domain.ts

From my understanding traefik labels are evaluated in order, the latest ones having the priority to override the first ones
I was personally unable to add CORS using traefik middlewares to some of my services since dokploys traefik middleware settings were overriding mine.
By prepending labels instead of adding them at the end this should allow the customization of traefik labels while still retaining the same functionality for whoever doesnt need it
I really hope I haven't missed something trivial :D

Allow traefik labels customization in docker-composes

---

apps/dokploy/components/dashboard/application/general/show.tsx
apps/dokploy/drizzle/0078_uneven_omega_sentinel.sql
apps/dokploy/drizzle/meta/0078_snapshot.json
apps/dokploy/drizzle/meta/_journal.json
apps/dokploy/package.json
packages/server/src/db/schema/application.ts
packages/server/src/db/schema/schema.dbml
packages/server/src/services/application.ts
packages/server/src/services/compose.ts
packages/server/src/utils/builders/docker-file.ts
packages/server/src/utils/builders/heroku.ts
packages/server/src/utils/builders/nixpacks.ts
packages/server/src/utils/builders/paketo.ts
packages/server/src/utils/builders/railpack.ts

- Introduced a new boolean column `cleanCache` in the application schema to manage cache cleaning behavior.
- Updated the application form to include a toggle for `cleanCache`, allowing users to enable or disable cache cleaning.
- Enhanced application deployment logic to utilize the `cleanCache` setting, affecting build commands across various builders (Docker, Heroku, Nixpacks, Paketo, Railpack).
- Implemented success and error notifications for cache updates in the UI.

feat(application): add cleanCache feature to application management

---

apps/dokploy/components/ui/input.tsx

This PR resolves the issue where the numeric input field would always retain the value `0`, making it difficult to delete or update the input properly. Previously, when a user entered a new value, it would either start with `0` (e.g., `05`) or require manually deleting the `0`.
To fix this issue, the **Focus Lost (Blur)** event has been implemented with the following improvements:
- When the input loses focus and is empty, its value **automatically** resets to `0`.
- This allows users to clear the field entirely and enter new values without restrictions.
- The input behavior is now more intuitive and user-friendly.
This enhancement ensures a smoother and more natural numeric input experience, improving usability and preventing unintended formatting issues.

fix(ui): Prevent Zero from Persisting in Numeric Input

---

apps/dokploy/components/dashboard/application/advanced/cluster/show-cluster-settings.tsx
apps/dokploy/components/dashboard/settings/notifications/handle-notifications.tsx
apps/dokploy/components/dashboard/settings/web-server/manage-traefik-ports.tsx
apps/dokploy/components/ui/input.tsx

This PR addresses multiple issues related to numeric input handling in the **Swarm Cluster settings**, **Traffic Port Mappings**, and **Email Notification configurations**. It ensures that users can properly clear and update numeric fields without unintended behavior.  
A previous commit attempted to fix a similar issue but did not work as expected. Apologies for any inconvenience caused. This PR introduces a more robust solution that correctly handles all cases without breaking existing functionality.  
**Before:**  
- When trying to delete the value in the **Replicas** field, it would automatically revert to ``0``.  
- This caused an issue similar to the previous numeric input bug.  
**After:**  
- If left empty, the field now triggers an error message: ``"Replicas must be at least …

fix(ui): Improve Numeric Input Handling in Swarm Cluster Settings, Traefik Port Mappings, and Email Notifications

---

packages/server/src/setup/server-setup.ts

In this PR, in addition to installing unzip and tar mentioned in #1482, sudo is also installed. This is because sudo is not installed by default after installing Alpine Linux, to prevent users from not having it installed.

fix(server-setup): resolve Alpine Linux compatibility issues 

---

packages/server/src/utils/backups/index.ts

The auto deletion of db backups wasn't working after the server update. I investigated the issue. It seems the bullmq worker job processing is not applicable for self-hosted instances. So, we need to make this change for auto deletion to work.

fix(backups): auto deletion of backups

---

apps/dokploy/components/dashboard/database/backups/add-backup.tsx
apps/dokploy/components/dashboard/database/backups/restore-backup.tsx
apps/dokploy/components/dashboard/database/backups/show-backups.tsx
apps/dokploy/drizzle/0082_clean_mandarin.sql
apps/dokploy/drizzle/0083_parallel_stranger.sql
apps/dokploy/drizzle/meta/0082_snapshot.json
apps/dokploy/drizzle/meta/0083_snapshot.json
apps/dokploy/drizzle/meta/_journal.json
apps/dokploy/pages/dashboard/settings/server.tsx
apps/dokploy/server/api/routers/backup.ts
apps/dokploy/server/api/routers/user.ts
packages/server/src/db/schema/backups.ts
packages/server/src/db/schema/user.ts
packages/server/src/index.ts
packages/server/src/utils/backups/index.ts
packages/server/src/utils/backups/utils.ts
packages/server/src/utils/backups/web-server.ts
packages/server/src/utils/restore/index.ts
packages/server/src/utils/restore/web-server.ts

709 back ups for dokploy

---

apps/dokploy/components/dashboard/projects/show.tsx

Enhance the project grid for 2XL resolution by increasing the width of the thumbnails.
Before:
After:

feat: improve projects grid

---

packages/server/src/utils/builders/static.ts

Sensitive files were exposed from Nginx. I added a .dockerignore file to exclude them during the `COPY . .` command.

fix(security): remove sensitive files on static build

---

apps/dokploy/__test__/traefik/server/update-server-config.test.ts
apps/dokploy/components/dashboard/settings/web-domain.tsx
apps/dokploy/drizzle/0084_thin_iron_lad.sql
apps/dokploy/drizzle/meta/0084_snapshot.json
apps/dokploy/drizzle/meta/_journal.json
apps/dokploy/server/api/routers/settings.ts
packages/server/src/db/schema/user.ts
packages/server/src/utils/traefik/web-server.ts

- Introduced a new boolean field 'https' in the user schema to manage HTTPS settings.
- Updated the web domain form to include an HTTPS toggle, allowing users to enable or disable HTTPS.
- Enhanced validation logic to ensure certificate type is required when HTTPS is enabled.
- Modified Traefik configuration to handle HTTPS routing based on user settings.

feat(settings): add HTTPS support and update user schema

---

packages/server/src/utils/backups/web-server.ts
packages/server/src/utils/restore/web-server.ts

- Updated the backup command in runWebServerBackup to suppress output by redirecting it to /dev/null.
- Modified the restore command in restoreWebServerBackup to also suppress output during the extraction of backups.

fix(backups): suppress output during backup and restore processes

---

apps/dokploy/pages/dashboard/project/[projectId].tsx

Update bulk action endpoints for database services:
- Use `/api/trpc/redis.start` and `/api/trpc/redis.stop` for Redis
- Use `/api/trpc/postgres.start` and `/api/trpc/postgres.stop` for PostgreSQL
- Retain `/api/trpc/compose.start` and `/api/trpc/compose.stop` for Docker Compose services
Tested with a project including Gitea, Redis, and PostgreSQL. Bulk start/stop operations now function correctly for all service types.
Closes #1626

fix: resolve incorrect endpoints for database bulk actions (#1626)

---

apps/dokploy/pages/dashboard/project/[projectId].tsx
packages/server/src/utils/traefik/web-server.ts

`passHostHeader` was moved to  the `servers` field, but should be inside the `loadBalancer` field. i.e. the same level as `servers`

Fix(Traefik) Move `passHostHeader` to correct indentation

---

apps/dokploy/components/dashboard/application/preview-deployments/show-preview-settings.tsx

Fixes incorrect toast message when toggling 'Preview Deployments'.

fix: correct message on preview deployments disabling

---

apps/dokploy/components/dashboard/settings/profile/enable-2fa.tsx

- Simplified the password submission and verification processes.
- Introduced a new state for OTP input, allowing for direct user input.
- Updated error handling to provide clearer feedback during the verification process.
- Enhanced the user experience by resetting the OTP value when switching steps and modifying the form structure for better clarity.
https://github.com/Dokploy/dokploy/issues/1716, #1715,#1714

Refactor 2FA enablement flow in Enable2FA component

---

packages/server/src/utils/backups/web-server.ts

- Added error handling to check for the existence of the PostgreSQL container before executing the backup command.
- Updated the backup command to use the retrieved container ID, ensuring the command runs correctly.

Enhance PostgreSQL backup command in web server utility

---

CONTRIBUTING.md

Just a couple of small updates to contributing.md I think might be helpful:
```We use Node v20.9.0 and recommend this specific version. If you have nvm installed, you can run `nvm install 20.9.0 && nvm use` in the root directory.```
When I tried to run it with v22, I had errors in the console.
and
`Note: this project uses Biome. If your editor is configured to use another formatter such as Prettier, it's recommended to either change it to use Biome or turn it off.`
If your editor is configured to use prettier and eslint have any type of ADD (I don't usually, but it's not too late to start...), installing and setting up the Biome addon will stop the editor from reformatting needlessly.

docs(contributing): tips added for nvm use and biome ide addon

---

apps/dokploy/components/dashboard/settings/git/gitlab/add-gitlab-provider.tsx
apps/dokploy/components/dashboard/settings/git/gitlab/edit-gitlab-provider.tsx
apps/dokploy/pages/dashboard/project/[projectId].tsx
packages/server/src/utils/providers/gitlab.ts

Since it's common having multiple groups in a single GitLab instance, we need to support comma separated group names. This PR add support for handling multiple GitLab group names with a single GitLab provider.

feat(gitlab): add support for multiple group names with a single provider

---

apps/dokploy/components/dashboard/application/general/generic/show.tsx
apps/dokploy/components/dashboard/settings/ai-form.tsx
apps/dokploy/components/dashboard/settings/certificates/show-certificates.tsx
apps/dokploy/components/dashboard/settings/cluster/registry/show-registry.tsx
apps/dokploy/components/dashboard/settings/destination/show-destinations.tsx
apps/dokploy/components/dashboard/settings/notifications/show-notifications.tsx
apps/dokploy/components/dashboard/settings/ssh-keys/show-ssh-keys.tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/application/[applicationId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/compose/[composeId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/mariadb/[mariadbId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/mongo/[mongoId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/mysql/[mysqlId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/postgres/[postgresId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/redis/[redisId].tsx

Fixes #1731
[output.webm](https://github.com/user-attachments/assets/c91325f4-4d98-432f-a714-66003a2a21c8)

Fix overflow toolbar

---

CONTRIBUTING.md
Dockerfile
apps/dokploy/components/layouts/user-nav.tsx
packages/server/src/setup/server-setup.ts

This PR updates Nixpacks from version 1.29.1 to 1.35.0.
Closes #1724
- Updated `Dockerfile` - Changed ARG NIXPACKS_VERSION from 1.29.1 to 1.35.0
- Updated `packages/server/src/setup/server-setup.ts` - Changed NIXPACKS_VERSION from 1.29.1 to 1.35.0
- Updated `CONTRIBUTING.md` - Updated the Buildpacks installation command to reference the latest version (0.35.0)
All tests have been run locally and pass successfully:
```
> dokploy@v0.21.7 test /home/alexander/Documents/GitHub/dokploy/apps/dokploy
> vitest --config __test__/vitest.config.ts
Test Files  32 passed (32)
Tests  160 passed (160)
```

Update Nixpacks to 1.35.0

---

apps/dokploy/components/dashboard/compose/general/compose-file-editor.tsx

https://github.com/Dokploy/dokploy/issues/1736
Please note that I'm not very used to react, please take the time to check my change.
Sincerely,
Max

Add Ctrl+S keyboard shortcut to save compose file

---

apps/dokploy/components/dashboard/settings/servers/actions/show-dokploy-actions.tsx
apps/dokploy/server/api/routers/settings.ts

Implement 'Clean Redis' and 'Reload Redis' actions in the dashboard settings. These actions allow users to flush all data in Redis and restart the Redis service, respectively. Update the API to handle these new mutations with appropriate error handling and success notifications.

Add Redis management actions to server settings

---

apps/dokploy/drizzle/0089_noisy_sandman.sql

- Modified the `backup` table to include a new `appName` column, which is now populated with a dynamically generated name combining random selections from predefined arrays and a random hash.
- Ensured the `appName` column is set to NOT NULL after the update, maintaining data integrity.
- Retained existing columns and added new ones for improved backup management.

Enhance backup table schema with dynamic appName generation

---

packages/server/src/services/compose.ts
packages/server/src/services/settings.ts

- Updated the `removeCompose` function to include a command for disconnecting the Docker network before removing the stack or compose application, improving cleanup reliability.
- Removed unnecessary console logging in the `getServiceImageDigest` function to streamline output and enhance code clarity.

Enhance compose removal process by adding network disconnection command

---

bun.lock
packages/server/src/utils/backups/utils.ts

Sample query:
```bash
devops@dsg-production:~$ docker ps --filter "status=running" --filter "label=com.docker.stack.namespace=revantine-store-production-opcrzw" --filter "name=revantine-store-production-opcrzw_mariadb*"
CONTAINER ID   IMAGE        COMMAND                  CREATED             STATUS             PORTS      NAMES
d47850477ea1   mariadb:11   "docker-entrypoint.s…"   About an hour ago   Up About an hour   3306/tcp   revantine-store-production-opcrzw_mariadb.1.k7wsxd67l8m8vldbhppri90vd
```
Explanation:
- `--filter "name=..."`: This filters based on the container name.
- `revantine-store-production-opcrzw_mariadb*`: This is the pattern for the name. It matches container names that start with your stack's namespace (`revantine-store-production-opcrzw`), followed by an underscore, …

Fix container not found upon backup/restore on compose stack

---

packages/server/src/utils/restore/utils.ts

Avoid errors during restoration when the original owning roles do not exist on the target PostgreSQL server.

Add no owner options to pg_restore

---

apps/dokploy/components/dashboard/application/domains/show-domains.tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/compose/[composeId].tsx

Domain buttons are not usuable for smaller desktop screenwidths, e.g. when
- using Zen Browser with Sidebar
- using Tablet/Ipad
- using a window manager with two applications side by side
This PR addresses the responsiveness design across all screen widths
[before.webm](https://github.com/user-attachments/assets/2555debc-5d69-4e9f-a558-5e4236ecd622)
[after.webm](https://github.com/user-attachments/assets/b716dfe0-41d4-4362-9e8a-f45b62dfee63)
**Edit:** have also fixed the toolbar responsiveness in [136570b](https://github.com/Dokploy/dokploy/pull/1891/commits/136570b36cd3cf5f4dbefe823fa57eb972b7607a)

Fix domain responsiveness

---

apps/dokploy/components/dashboard/application/deployments/show-deployments.tsx

This fixes an issue where `Compose` auto-deploy URLs were displayed without the `/compose` in the URL path.
For type `Application`:
For type `Compose`:
fixes: #1831

fix: Missing `/compose` in auto-deploy URL

---

apps/dokploy/components/dashboard/application/general/generic/save-bitbucket-provider.tsx
apps/dokploy/components/dashboard/application/general/generic/save-git-provider.tsx
apps/dokploy/components/dashboard/application/general/generic/save-gitea-provider.tsx
apps/dokploy/components/dashboard/application/general/generic/save-github-provider.tsx
apps/dokploy/components/dashboard/application/general/generic/save-gitlab-provider.tsx
apps/dokploy/components/dashboard/compose/general/generic/save-bitbucket-provider-compose.tsx
apps/dokploy/components/dashboard/compose/general/generic/save-git-provider-compose.tsx
apps/dokploy/components/dashboard/compose/general/generic/save-gitea-provider-compose.tsx
apps/dokploy/components/dashboard/compose/general/generic/save-github-provider-compose.tsx
apps/dokploy/components/dashboard/compose/general/generic/save-gitlab-provider-compose.tsx

I've spent more time than what I want to admit trying to figure out why my github apps were not deploying correctly. It turns out that dokploy is using `micromatch` for the watch path. The current UI has the following placeholder:
Those examples will only match files that are direct descendants of src, like src/index.js, but not src/module/file.js. In this PR I've modified the placeholder so that it's more informative and does not put user in the wrong path.

fix: more informative placeholder for watch path

---

apps/dokploy/Dockerfile
packages/server/src/setup/server-setup.ts

problem: when cloning repositories with LFS files, these files was not properly cloned resulting in faulty deployments.
cause: Git LFS was not supported in the dokploy image
fix: installed git-lfs and hooked it up to Git inside the Dokploy image (Modified `app/Dockerfile`)
test: i haven't built the Dokploy image to test it, but executing the added commands into the Dokploy container `sh` fixes the issue.

fix: installed git-lfs in docker image

---

apps/dokploy/components/dashboard/compose/general/randomize-compose.tsx

I added this change in the isolated deployment PR #1917, but forgot to make the same changes in the randomize compose.
Basically awaiting the randomize update & refetch before printing the success message. This way, errors will also be caught and handled properly.

fix: randomize-compose missing await

---

apps/dokploy/server/api/routers/compose.ts

Changing the return value from ```null``` to ```compose```, the variable that contain newly created compose informations, fixing the issue #2006 
Here an example with the swagger and the creation of a compose with wordpress template

fix api: return compose informations when created from template

---

apps/dokploy/server/api/routers/settings.ts

- Implemented a new admin procedure to fetch cloud IPs from environment variables.
- Returns an empty array if not in cloud mode.

feat(settings): add query to retrieve Dokploy cloud IPs

---

packages/server/src/utils/builders/index.ts
packages/server/src/utils/cluster/upload.ts

- Updated the logic for constructing the registry tag in the uploadImage and uploadImageRemoteCommand functions to ensure correct formatting.
- Removed unnecessary path imports and streamlined the code for better readability.

fix(upload): refactor registry tag construction for image uploads

---

README.md

Documentation:
- Inline anchor and image tags in Hero Sponsors, Premium Supporters, and Elite Contributors sections to remove blue underlines
| Before | After |
|--------|--------|
| ![スクリーンショット 2025-06-30 170342](https://github.com/user-attachments/assets/f682f266-6bc4-4115-9d5a-be6988ff884d) | ![スクリーンショット 2025-06-30 170352](https://github.com/user-attachments/assets/b9afd419-b131-42ba-8a83-67edf907bbcf) | 
Previously, the images were displayed with line breaks between them, causing blue link lines to appear, which disrupted the clean look of the images. By removing these line breaks, the images now appear without the blue link lines, providing a more cohesive and visually appealing README.

docs: remove blue underlink from README.md

---

apps/dokploy/setup.ts
packages/server/src/setup/traefik-setup.ts

Hi,
- Fixes #2029 
- Added the pulling of the traefik image name/version during the setup (`pnpm run dokploy:setup`) when it's not present locally otherwise it throws an error if you don't have it.
- I didn't add any tests because it seems like there isn't any on the setup part ?

fix(traefik-setup): now pulling the traefik image to make it sure it's present locally

---

apps/dokploy/components/dashboard/application/general/generic/save-gitlab-provider.tsx
apps/dokploy/components/dashboard/compose/general/generic/save-gitlab-provider-compose.tsx
packages/server/src/utils/providers/gitlab.ts

- Changed the repository selection logic in SaveGitlabProvider and SaveGitlabProviderCompose components to use the repository URL for better accuracy.
- Updated the condition for displaying the selected repository in the CheckIcon component to compare against the gitlabPathNamespace instead of the repository name.
- Refactored the getGitlabRepositories function to simplify the group name check logic.

fix(gitlab): update repository selection to use URL instead of name

---

README.md

Fix broken sponsor images and cleanup HTML structure in the [README](https://github.com/Dokploy/dokploy/blob/canary/README.md)
Documentation:
- Update sponsor image tags with correct src paths and width attributes
- Simplify HTML structure by removing redundant wrappers and inline styles
- Comment out empty placeholders for Premium Supporters and Elite Contributors
At #2108, I updated the [README.md](https://github.com/Dokploy/dokploy/blob/canary/README.md) to fix blue underlink.
However, the sponsers images styles were broken at that time.
This PR improves that appearance.
In addition, according to [GitHub Markup](https://github.com/github/markup) ...
> 2. The HTML is sanitized, aggressively removing things that could harm you and your kin—such as script tags, inline-styles, and class or …

docs: fix broken README.md sponsers images

---

apps/dokploy/server/api/routers/project.ts

- Extracted and modified the application name by removing the suffix after the last hyphen when duplicating various application types (Postgres, MariaDB, Mongo, MySQL, Redis, Compose).
- Ensured consistent naming for duplicated applications across different database types.

feat(project): update application name handling during duplication

---

apps/dokploy/components/dashboard/application/general/generic/show.tsx
apps/dokploy/components/dashboard/compose/general/generic/show.tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/application/[applicationId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/compose/[composeId].tsx
apps/dokploy/tailwind.config.ts

There are improvements:
- Removed `overflow-x: scroll` as this CSS creates empty scrollbar at wide screens.
- Changed grid layout to flex since this is not a table view, but a row of elements.
- Removed double `overflow-x: scroll` and `overflow-y: hidden` because in the first case you get a double scroll, and in the second case something may be unexpectedly hidden.
Now the entire tablist is a row of elements that are horizontally located with some indentation from each other. It is wrapped by an element that has a fixed width of 100%. It is responsible for scrolling if something does not fit.
- Fixed provider tabs layout.
- Fixed not working min-* max-* tailwind variants: `warn - The 'min-*' and 'max-*' variants are not supported with a 'screens' configuration containing mixed units`. As …

fix(ui): tabs overflow and Tailwind config

---

apps/dokploy/components/dashboard/application/advanced/traefik/show-traefik-config.tsx
apps/dokploy/components/dashboard/application/deployments/show-deployment.tsx
apps/dokploy/components/dashboard/docker/config/show-container-config.tsx
apps/dokploy/components/dashboard/docker/logs/docker-logs-id.tsx
apps/dokploy/components/dashboard/docker/logs/line-count-filter.tsx
apps/dokploy/components/dashboard/project/duplicate-project.tsx
apps/dokploy/components/dashboard/projects/show.tsx
apps/dokploy/components/dashboard/settings/servers/setup-server.tsx
apps/dokploy/components/dashboard/settings/servers/welcome-stripe/create-ssh-key.tsx
apps/dokploy/components/dashboard/swarm/monitoring-card.tsx

This PR fixes a regression where the `overflow-y-auto` classname was accidentally removed from the Docker logs viewer components, causing scrolling issues.
- Restored `overflow-y-auto` to the main logs container in `docker-logs-id.tsx`
- Added `overflow-y-auto` to the line count filter dropdown in `line-count-filter.tsx`
These overflow classes are essential for proper scrolling behavior in:
- The main logs viewer container (720px fixed height)
- The line count filter dropdown (300px max height)
Without these classes, users were unable to scroll through logs when content exceeded the container height.
- `apps/dokploy/components/dashboard/docker/logs/docker-logs-id.tsx`
- `apps/dokploy/components/dashboard/docker/logs/line-count-filter.tsx`
#2186

fix(logs): Restore overflow classnames in logs components

---

pnpm-workspace.yaml

Chores:
- Remove `apps/monitoring` from `pnpm-workspace.yaml` packages list
At #1267, [`apps/monitoring`](https://github.com/Dokploy/dokploy/tree/canary/apps/monitoring) was added to [`pnpm-workspace.yaml`](https://github.com/Dokploy/dokploy/blob/canary/pnpm-workspace.yaml).
However, pnpm can't manage it due to [Go](https://go.dev/) application.

chore: remove `apps/monitoring` from `pnpm-workspace.yaml`

---

.github/workflows/deploy.yml
.github/workflows/dokploy.yml

Update deploy and dokploy GitHub Actions workflows to remove obsolete branch filters and enable manual dispatch
CI:
- Remove custom branch filters from push triggers in deploy and dokploy workflows
- Add workflow_dispatch triggers to allow manual runs of deploy and dokploy workflows
When a workflow is configured to run on the `workflow_dispatch` event, you can run the workflow using the Actions tab on GitHub.
You don't need to add custom branch to workflow file because you can run a GitHub Actions manually with the branch to test.
[Manually running a workflow](https://docs.github.com/en/actions/how-tos/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow)

ci: remove custom branch and add workflow_dispatch event

---

apps/api/package.json
apps/dokploy/package.json
apps/schedules/package.json
package.json
packages/server/package.json

Update the pnpm version and enforce engine constraints across all packages.
Build:
- Bump packageManager pnpm version to v9.12.0 in all package.json files
- Add engines field to require Node >=20.16.0 and pnpm >=9.12.0 in all packages
Dockerfiles specified [pnpm@9.12.0](https://github.com/pnpm/pnpm/releases/tag/v9.12.0) at [`19f7465`](https://github.com/Dokploy/dokploy/commit/19f746591016dc3f456d9bea015d3deb38819072).
It's good to match [`packageManager` field in `package.json` for corepack](https://github.com/nodejs/corepack/tree/main?tab=readme-ov-file#when-authoring-packages).

chore(package): version up pnpm to v9.12.0

---

apps/dokploy/components/dashboard/application/deployments/show-deployments.tsx
apps/dokploy/components/dashboard/application/volume-backups/restore-volume-backups.tsx
apps/dokploy/components/dashboard/application/volume-backups/show-volume-backups.tsx
apps/dokploy/components/dashboard/compose/general/generic/show.tsx
apps/dokploy/pages/api/deploy/github.ts
apps/dokploy/pages/dashboard/project/[projectId]/services/application/[applicationId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/compose/[composeId].tsx
apps/dokploy/server/api/root.ts
apps/dokploy/server/api/routers/deployment.ts
apps/dokploy/server/api/routers/docker.ts
apps/dokploy/server/api/routers/mount.ts
apps/dokploy/server/api/routers/swarm.ts
apps/dokploy/server/api/routers/volume-backups.ts
apps/dokploy/setup.ts

Refactor the dokploy application by linting and organising imports, removing dead code, and improving code style consistency.
Enhancements:
- Standardise and alphabetise imports across server API routers and React components
- Remove unused and redundant imports to clean up codebase
- Add missing utility imports where necessary
- Tidy up code formatting and grouping for consistency
```bash
pnpm biome check apps/dokploy
```

refactor: lint and sort import on dokploy application

---

packages/server/src/db/schema/deployment.ts
packages/server/src/db/schema/rollbacks.ts
packages/server/src/db/schema/user.ts
packages/server/src/db/schema/volume-backups.ts
packages/server/src/services/deployment.ts
packages/server/src/services/rollbacks.ts
packages/server/src/services/volume-backups.ts
packages/server/src/utils/docker/collision.ts
packages/server/src/utils/traefik/application.ts
packages/server/src/utils/traefik/middleware.ts
packages/server/src/utils/volume-backups/backup.ts
packages/server/src/utils/volume-backups/restore.ts
packages/server/src/utils/volume-backups/utils.ts

Standardize and clean up import statements across the server package by sorting, grouping type imports, and removing duplicates.
Enhancements:
- Sort and group imports alphabetically and separate type imports from value imports in server modules
- Remove duplicate and unused imports across various server files for consistency
```bash
pnpm biome check packages/server
```

refactor: lint and sort imports on dokploy/server

---

.vscode/extensions.json
.vscode/settings.json

Add VSCode workspace configurations to recommend the Biome extension and apply its settings
Chores:
- Add .vscode/extensions.json to recommend the Biome editor extension
- Add .vscode/settings.json to configure Biome as the default formatter and enable its features on save

chore: add biome settings for vscode editor

---

apps/dokploy/components/dashboard/project/add-application.tsx
apps/dokploy/components/dashboard/project/add-compose.tsx
apps/dokploy/components/dashboard/project/add-database.tsx
apps/dokploy/components/dashboard/project/add-template.tsx
apps/dokploy/components/dashboard/project/ai/step-one.tsx
apps/dokploy/components/dashboard/settings/git/show-git-providers.tsx

A couple of days ago, I came across a [YouTube video](https://youtu.be/ELkPcuO5ebo?t=803) where the creator **Dreams of Code** highlighted some valid UI/UX concerns. I completely agreed with the points raised and decided to implement improvements directly addressing them.
1. **Unnecessary Server Selection**  
The UI showed a server selection dropdown even when no servers were available (e.g., single-instance self-hosted setup), which could confuse users.
2. **Unclear Git Provider Status**  
There was no obvious indication that a Git provider (e.g., GitHub, GitLab) required additional setup steps to be fully configured.
---
- Conditionally render server selection fields in:
- `AddApplication`
- `AddCompose`
- `AddDatabase`
- `AddTemplate`
- `StepOne`
- Display a clear "Action Required" …

feat(ux): Improve UX Based on Community Feedback

---

CONTRIBUTING.md

Use [GitHub alert syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) in contributing guide and update [localtunnel](https://localtunnel.app/) instructions
Enhancements:
- Switch localtunnel command to use pnpm dlx instead of bunx
Documentation:
- Replace plain note with GitHub markdown alert for Biome formatter
- Add hyperlink to localtunnel in the installation instructions

docs(contributing): use Alerts syntax of GitHub markdown

---

apps/dokploy/components/shared/ChatwootWidget.tsx
apps/dokploy/components/shared/alert-block.tsx
apps/dokploy/components/shared/breadcrumb-sidebar.tsx
apps/dokploy/components/shared/code-editor.tsx
apps/dokploy/components/shared/date-tooltip.tsx
apps/dokploy/components/shared/drawer-logs.tsx
apps/dokploy/components/shared/toggle-visibility-input.tsx

Apply linting and styling refinements across shared component files to improve consistency and readability.
Enhancements:
- Reorder and consolidate imports, and remove unused imports in shared components for a cleaner codebase.
- Simplify conditional logic and inline temporary variables in code-editor and toggle-visibility-input components.
- Standardize naming and usage patterns by renaming iteration variables, unifying window.chatwootSDKReady assignment, and fixing placement enum ordering.
- Adjust spacing and JSX formatting in breadcrumb-sidebar, drawer-logs, date-tooltip, and alert-block components for consistent styling.

refactor: lint apps/components/shared files

---

.github/workflows/create-pr.yml

Remove unused id fields from several steps in the create-pr GitHub Actions workflow
CI:
- Remove unused id from "Get version from package.json" step
- Remove unused id from "Get latest GitHub tag" step
- Remove unused id from "Compare versions" step
- Remove unused id from "Check if a PR already exists" step

ci(create-pr): remove unused id

---

packages/server/src/services/settings.ts

Currently, updating a remote server's Traefik environment updates the local server's Traefik container instead instead.
The issue here is that the `serverId` can be passed in two different ways to `writeTraefikSetup`. This PR has the `serverId` parameter default to `input.serverId` if it isn't passed in. 
Fixes #2351 
Updating traefik env on a remote server is successful:
Inspecting the traefik container on remote server shows the updated env:

fix(traefik): on setup support serverId as parameter and input

---

apps/dokploy/components/dashboard/project/add-template.tsx

This PR fixes some wrong formatting that happened when using the template search function (as described in #2382).
I believe the issue was caused by duplicate keys, as the key prop only contained the template ID. This resulted in multiple elements sharing the same key, which caused React to incorrectly update the templates due to the ambiguity.
FIXES #2382

fix(template): duplicate key issue causing wrong formatting in template search

---

apps/dokploy/hooks/use-keyboard-nav.tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/application/[applicationId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/compose/[composeId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/mariadb/[mariadbId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/mongo/[mongoId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/mysql/[mysqlId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/postgres/[postgresId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/redis/[redisId].tsx

yesterday i added the application page shortcuts and this is just for more pages to have similar functionality. all the database pages and the compose page now have the shortcuts

add keyboard nav for compose/database pages

---

apps/dokploy/components/ui/dialog.tsx

Changes display layout to fix overflow inside the modals with scrollable content like Templates.
This is the reason why the content is cut off and the second scrollbar appears.
Before:
https://github.com/user-attachments/assets/5d11dc96-76f4-460f-a03f-dff8e6f562b5
After:
https://github.com/user-attachments/assets/1e65d8d6-1586-4573-9928-e106713d5415

fix(ui): modal double scroll

---

apps/dokploy/components/ui/dialog.tsx

Clicking outside of tag dropdown in template modal closes the modal cause of conditional pointer events transparency.
Caused:
The problem was that when the popover appeared, the radix assigned the `pointer-event: none` to the modal window.
This made it transparent to the click, which resulted in the backdrop being clicked and subsequently closed.
Changes:
Make modal pointer events defined to prevent the logic described above.
Closes #2400 
https://github.com/user-attachments/assets/bdf1835b-0c38-41e8-b4b7-9631d76f5667

fix(ui): modal popover handle close

---

apps/dokploy/components/ui/sidebar.tsx

Changes the scrollbar styles to eliminate its hiding/appearing when opening a popover, which results in content shifting.
Before:
https://github.com/user-attachments/assets/7e8103b2-0bc3-4c30-9192-ad0d42c0c110
After:
https://github.com/user-attachments/assets/efa16a81-0eb8-4704-827c-1fe691aaafd1

fix(ui): scroll gutters stable

---

apps/dokploy/components/dashboard/organization/handle-organization.tsx

When the update organization operation is performed, the `activeOrganization?.name` value is not invalidated. The new organization name value is not visible without refreshing the page, and the old organization name value is rendered.
https://github.com/user-attachments/assets/1bec3e16-0db7-4e24-8a5a-214fc90c4f8e

fix(organization): integrate active organization refetching on update/create

---

apps/dokploy/setup.ts
packages/server/src/setup/traefik-setup.ts
packages/server/src/utils/docker/domain.ts

Bump Traefik to v3.2.2 and enable swarm network label in domain compose configuration
Enhancements:
- Include traefik.swarm.network=dokploy-network label alongside the existing docker network label
- Update default Traefik version fallback from 3.1.2 to 3.2.2
According to [v3.1 to v3.2 migration guide](https://doc.traefik.io/traefik/v3.2/migration/v3/#v31-to-v32) ...
> In v3.2.2, the `traefik.docker.network` and `traefik.docker.lbswarm` labels have been deprecated, please use the `traefik.swarm.network` and `traefik.swarm.lbswarm` labels instead.
So I added the `traefik.swarm.network` label check like `traefik.docker.network`.
- [Migration: Steps needed between the versions](https://doc.traefik.io/traefik/v3.2/migration/v3/#migration-steps-needed-between-the-versions)
- [Comparing …

feat: bump Traefik v3.2.2 and add swarm network label 

---

apps/dokploy/pages/index.tsx

This PR adds auto-focus functionality to the two-factor authentication form. When the OTP input component becomes visible after successful login form submission, the first input field automatically receives focus, improving the user experience by eliminating the need for users to manually click on the input field.
- [* ] You created a dedicated branch based on the `canary` branch.
- [ *] You have read the suggestions in the CONTRIBUTING.md file https://github.com/Dokploy/dokploy/blob/canary/CONTRIBUTING.md#pull-request
- [ *] You have tested this PR in your local instance.

feat: add autofocus to two-factor authentication input

---

apps/dokploy/components/dashboard/projects/show.tsx
apps/dokploy/components/dashboard/search-command.tsx
apps/dokploy/components/shared/focus-shortcut-input.tsx
apps/dokploy/pages/dashboard/project/[projectId]/environment/[environmentId].tsx

Add focus to search input by pressing Cmd + K shortcut. It's usual shortcut on most sites to open Command Palette, but since we don't have it we can map it to focus at input. 
We could probably add Command Palette in future so it's discussible should we take this shortcut or try to remap it to Cmd + F or Cmd + Shift + F
closes #2514

feat(input): Add focus by Cmd + K shortcut to search input

---

packages/server/src/utils/providers/github.ts

Fixes the incorrect spelling of cloning on the github import process.
N/A

 fix: fix typo for Github clone

---

apps/dokploy/components/dashboard/project/duplicate-project.tsx

**Problem:** When duplicating services to the same project/environment, the services list doesn't refresh automatically - users need to hard refresh to see duplicated services.
**Solution:** Added proper cache invalidation in `DuplicateProject` component:
- Invalidate `environment.one` query to refresh services list
- Invalidate `environment.byProjectId` query to update environment selector
- Handle same-environment duplication to refresh current page
**Files Changed:**
- `apps/dokploy/components/dashboard/project/duplicate-project.tsx`
**Result:** Services list now refreshes automatically after duplication, no hard refresh needed.
Fixes #2565

feat: Auto-refresh services list when duplicating to same environment

---

packages/server/src/utils/backups/utils.ts

Fixes locking on MariaDB backups described on issue #2443
- [] You have tested this PR in your local instance.
closes #2443

feat(backups): make mariadb backups non-blocking

---

packages/server/src/utils/providers/gitlab.ts

Cloning a GitLab repository for a compose service to a remote server incorrectly used the **branch** column from Postgres' **compose** table instead of the **gitlabBranch** column. As the **branch** column is _null_ for GitLab repositories cloning would result in an error.
Fixes #2623

Fix: Update gitlab.ts cloneRawGitlabRepositoryRemote to use gitlabBranch

---

apps/dokploy/components/dashboard/project/add-template.tsx

This PR fixes the shrinking behaviour of view mode icon button that can be observed on the "Create from Template" dialog on the project page.
**Before**
**After**

fix: prevent the shrinking of icon button for view mode on add template dialog

---

apps/dokploy/components/dashboard/projects/show.tsx

Fixes the issue where Compose service domains were not displaying in the projects dashboard dropdown menu. The domain display logic for Compose services was commented out, while Applications domains were working correctly.
- Template-deployed Compose services (like Nginx, WordPress, etc.) were not showing their configured domains in the projects dashboard
- Users could access the services via their domains, but the UI didn't display the domain links
- The Compose domain rendering code was completely commented out in `ShowProjects.tsx`
- Uncommented the Compose domain rendering logic in `/apps/dokploy/components/dashboard/projects/show.tsx`
- Fixed the data structure to properly iterate through `project.environments` and then `env.compose`
- Added proper condition checking for …

fix: Display Compose service domains in projects dashboard (#2606)

---

apps/dokploy/components/dashboard/projects/show.tsx

The "Most services" sorting option in the Projects page was not working correctly. It was sorting projects by the number of environments instead of the total number of services across all environments, resulting in ascending order instead of the expected descending order.
Updated the sorting logic in `apps/dokploy/components/dashboard/projects/show.tsx` to properly count total services across all environments by summing up:
- Applications
- MariaDB instances  
- MongoDB instances
- MySQL instances
- PostgreSQL instances
- Redis instances
- Compose services
- Modified the `services` case in the sorting switch statement
- Changed from `a.environments.length` to proper service counting logic
- Maintains existing display logic which was already correct
Verified the fix with test data showing …

Feat: "Most services" sorting to count total services across environments -2691 

---

packages/server/src/utils/providers/gitea.ts

Ensure Gitea HTTP connections are respected: when connecting via HTTP, subsequent Gitea operations (clone, API) now use HTTP instead of defaulting to HTTPS, keeping OAuth token authentication intact

feat: support cloning repositories over HTTP in Gitea integration

---

packages/server/src/services/compose.ts

The notifications for deployments did not take into account the environment in docker compose projects resulting in a 400.
This PR fixes this issue by adding the environment in the buildLink.
closes #2708

fix: add environment in buildLink for docker compose deploy notifications

---

apps/dokploy/components/dashboard/application/advanced/cluster/modify-swarm-settings.tsx

Docker Swarm uses nanoseconds for it's configs, so fixing the placeholder values so they are 10 seconds instead of 0.00001 seconds (which throws errors).
- [] You have tested this PR in your local instance.

Fix swarm settings config placeholders

---

packages/server/src/utils/traefik/application.ts
packages/server/src/utils/traefik/middleware.ts

If the middleware.yaml file was empty, the parse function returned null, causing below error later on in various parts of the code, since the result was being cast to an object without any validation:
> Cannot read properties of null
This makes the null fallback to an empty object.
closes #2754
before:

fix: return an empty object if yaml file is empty
