components/dashboard/projects/add.tsx
server/api/routers/project.ts

It was weird for me that after creating new project modal isn't closed and I'm still looking at project list, if think it's better UX when we automatically navigate user to new project

Automatically navigate to new project after creation

---

components/dashboard/application/domains/add-domain.tsx
components/dashboard/application/domains/update-domain.tsx

Doc: Update for the Prompt text.

doc: Update prompt text

---

components/dashboard/application/environment/show.tsx
components/dashboard/mariadb/environment/show-mariadb-environment.tsx
components/dashboard/mongo/environment/show-mongo-environment.tsx
components/dashboard/mysql/environment/show-mysql-environment.tsx
components/dashboard/postgres/environment/show-postgres-environment.tsx
components/dashboard/redis/environment/show-redis-environment.tsx
pages/dashboard/project/[projectId]/services/application/[applicationId].tsx
pages/dashboard/project/[projectId]/services/mariadb/[mariadbId].tsx
pages/dashboard/project/[projectId]/services/mongo/[mongoId].tsx
pages/dashboard/project/[projectId]/services/mysql/[mysqlId].tsx
pages/dashboard/project/[projectId]/services/postgres/[postgresId].tsx
pages/dashboard/project/[projectId]/services/redis/[redisId].tsx
server/api/routers/application.ts
server/api/routers/mariadb.ts
server/api/routers/mongo.ts
server/api/routers/mysql.ts
server/api/routers/postgres.ts
server/api/routers/redis.ts
server/db/schema/application.ts
server/db/schema/mariadb.ts
server/db/schema/mongo.ts
server/db/schema/mysql.ts
server/db/schema/postgres.ts
server/db/schema/redis.ts

Corrects a misspelling of "environment" everywhere I could find in the project.

fix(typo): enviroment -> environment

---

.dockerignore
docker/build.sh
docker/canary.sh
docker/push.sh
package.json
server/api/services/settings.ts

Includes canary scripts for test

feat: add canary builds for testing purposes

---

server/utils/builders/index.ts

fix: typo in index.ts

---

server/server.ts

fix(#42): initialize the database as a first service

---

server/server.ts

Correct server port log for non 3000 port

Correct server port log for non 3000 port

---

server/utils/docker/utils.ts

Here are my proposed changes
#66

fix: Properly parse environment variables

---

CONTRIBUTING.md

docs: reset password command fix

---

server/api/routers/admin.ts

fix(#93): extract all branches from repository

---

components/dashboard/application/advanced/ports/add-port.tsx

fix(#119): remove none ports

---

components/dashboard/application/general/deploy-application.tsx
components/dashboard/compose/general/deploy-compose.tsx
components/dashboard/mariadb/general/deploy-mariadb.tsx
components/dashboard/mongo/general/deploy-mongo.tsx
components/dashboard/mysql/general/deploy-mysql.tsx
components/dashboard/postgres/general/deploy-postgres.tsx
components/dashboard/redis/general/deploy-redis.tsx

refacto(#118): remove last toaster on start deployments

---

components/dashboard/application/advanced/traefik/update-traefik-config.tsx
components/dashboard/application/advanced/volumes/add-volumes.tsx
components/dashboard/application/environment/show.tsx
components/dashboard/compose/enviroment/show.tsx
components/dashboard/compose/general/compose-file-editor.tsx
components/dashboard/file-system/show-traefik-file.tsx
components/dashboard/mariadb/environment/show-mariadb-environment.tsx
components/dashboard/mongo/environment/show-mongo-environment.tsx
components/dashboard/mysql/environment/show-mysql-environment.tsx
components/dashboard/postgres/environment/show-postgres-environment.tsx
components/dashboard/redis/environment/show-redis-environment.tsx
components/dashboard/settings/web-server.tsx
components/dashboard/settings/web-server/show-main-traefik-config.tsx
components/dashboard/settings/web-server/show-server-middleware-config.tsx
components/dashboard/settings/web-server/show-server-traefik-config.tsx
components/shared/code-editor.tsx
components/ui/dialog.tsx
styles/globals.css

fix: env editor width overflow

---

server/utils/backups/mongo.ts

fix(#149): use database user in mongodump

---

components/dashboard/application/domains/generate-domain.tsx
components/dashboard/application/domains/show-domains.tsx
server/api/routers/domain.ts
server/api/services/domain.ts

Close #40 
We add a button to generate traefik.me domains automatically so now, you don't need to have a domain or use the ip:port to access to your service!

40 feature request automatically generates domains

---

components/dashboard/application/domains/generate-domain.tsx
components/dashboard/application/domains/generate-traefikme.tsx
components/dashboard/application/domains/generate-wildcard.tsx
server/api/routers/domain.ts
server/api/services/domain.ts

feat(#40):  traefik.me modals

---

components/dashboard/application/deployments/show-deployments.tsx
drizzle/0017_minor_post.sql
drizzle/0017_yummy_norrin_radd.sql
drizzle/meta/0017_snapshot.json
drizzle/meta/_journal.json
pages/api/deploy/[refreshToken].ts
pages/api/deploy/compose/[refreshToken].ts
server/api/routers/application.ts
server/api/routers/compose.ts
server/api/services/application.ts
server/api/services/compose.ts
server/api/services/deployment.ts
server/db/schema/deployment.ts
server/queues/deployments-queue.ts

147 add commit hash and commit message in the deployment list

---

components/dashboard/projects/show.tsx

refactor(#168): make project card be clickable everywhere

---

server/utils/databases/redis.ts

fix(#167): pass args in redis to require pass

---

components/dashboard/project/add-template.tsx

fix: avoid black background on light theme

---

server/setup/postgres-setup.ts
server/setup/redis-setup.ts
server/setup/registry-setup.ts
server/setup/traefik-setup.ts

Add constraints to each dokploy service to be only on the manager node

refactor(setup): add constraints to dokploy services

---

server/setup/postgres-setup.ts
server/setup/redis-setup.ts
server/setup/registry-setup.ts
server/setup/traefik-setup.ts

fix(#210): Make dokploy services automatically start when a crash or restart server

---

.github/workflows/pull-request.yml
.github/workflows/push.yml
Dockerfile
package.json

Split github workflows into multiple files to maintain readability
Possibly speed up docker build by splitting into multiple stages for caching

ci: split workflows to separate files

---

components/shared/toggle-visibility-input.tsx

I added a copy button to the visibility input so people can quickly copy text value to clipboard in just 1 click. I mainly use this for quickly get the database's external host url.

feat: add copy function to visibility input

---

Dockerfile
server/utils/builders/heroku.ts

feat(heroku-buildpacks): upgrade heroku to 24 version

---

components/dashboard/project/add-template.tsx
server/api/routers/compose.ts

refactor(templates): add tag input selector

---

server/utils/builders/docker-file.ts
server/utils/builders/utils.ts

refactor(dockerfile): create .env file when using dockerfile #227

---

components/dashboard/compose/logs/show.tsx
pages/dashboard/project/[projectId]/services/compose/[composeId].tsx
server/api/routers/docker.ts
server/api/services/docker.ts

fix: https://github.com/Dokploy/dokploy/issues/256

fix: docker compose logs

---

docker/prod.sh

Make the installation command as a ipv4 first and in the case is ipv6 we format to this structure: [ipv6]

refactor(script): make ipv4 first and format the url when is ipv6 #258

---

docker/prod.sh
server/setup/config-paths.ts

refactor(directories): add 600 permissions to SSH_PATH #262

---

components/dashboard/settings/web-server.tsx
server/api/routers/settings.ts
server/db/schema/admin.ts
server/setup/traefik-setup.ts

Add toggle to disable or enable the traefik dashbaord

feat(traefik): add toggle for disable the traefik dashboard

---

apps/dokploy/__test__/traefik/traefik.test.ts
apps/dokploy/components/dashboard/application/build/show.tsx
apps/dokploy/drizzle/0027_red_lady_bullseye.sql
apps/dokploy/drizzle/meta/0027_snapshot.json
apps/dokploy/drizzle/meta/_journal.json
apps/dokploy/server/api/routers/application.ts
apps/dokploy/server/db/schema/application.ts
apps/dokploy/server/utils/builders/docker-file.ts
apps/dokploy/server/utils/builders/nixpacks.ts
apps/dokploy/server/utils/builders/static.ts

Fix: https://github.com/Dokploy/dokploy/issues/294
I ran a temporary container to extract build artifacts, significantly reducing the build image size from approximately ~600MB to just ~40MB.

feat: new publish directory flag

---

apps/dokploy/components/dashboard/application/build/show.tsx
apps/dokploy/drizzle/0028_jittery_eternity.sql
apps/dokploy/drizzle/meta/0028_snapshot.json
apps/dokploy/drizzle/meta/_journal.json
apps/dokploy/server/db/schema/application.ts
apps/dokploy/server/utils/builders/index.ts

Fix: https://github.com/Dokploy/dokploy/issues/298

feat: static buildtype

---

apps/dokploy/server/utils/docker/utils.ts

fix(swarm): remove restart policy #306

---

apps/dokploy/components/dashboard/application/advanced/volumes/add-volumes.tsx
apps/dokploy/server/api/routers/compose.ts
apps/dokploy/templates/listmonk/index.ts
apps/dokploy/templates/plausible/index.ts
apps/dokploy/templates/utils/index.ts

File path input was missing from docker compose which was causing issues to have static files in templates #313

fix(template): add missing file path

---

apps/docs/content/docs/core/docker-compose/overview.mdx
apps/docs/package.json
pnpm-lock.yaml

Close #315, thanks to @yayza for the info!

fix(docs): update dependencies

---

apps/dokploy/server/utils/providers/git.ts

fix(git): don't add to ssh known host when is a http or https url

---

apps/dokploy/server/utils/providers/git.ts

fix(git): add --recursive-submodules flag

---

apps/dokploy/components/dashboard/application/deployments/show-deployments.tsx

How it looked: https://media.vladislav.ovh/u/KSuPAh.png
How it looks now: https://media.vladislav.ovh/u/eAfRYU.png

fix: responsive design in the project settings page

---

apps/dokploy/components/dashboard/settings/github/github-setup.tsx
apps/dokploy/pages/api/redirect.ts

fix(github): use github url to install the application #337

---

apps/dokploy/components/dashboard/settings/users/add-permissions.tsx
apps/dokploy/components/layouts/settings-layout.tsx
apps/dokploy/drizzle/0030_little_kabuki.sql
apps/dokploy/drizzle/meta/0030_snapshot.json
apps/dokploy/drizzle/meta/_journal.json
apps/dokploy/pages/dashboard/settings/ssh-keys.tsx
apps/dokploy/server/api/routers/settings.ts
apps/dokploy/server/api/routers/ssh-key.ts
apps/dokploy/server/db/schema/user.ts

282 add option to revert dokploy version opt in based auto updates

---

apps/dokploy/server/db/validations/index.ts

refactor: remove hostname regex

---

apps/dokploy/components/dashboard/application/advanced/ports/add-port.tsx
apps/dokploy/components/dashboard/application/advanced/ports/update-port.tsx
apps/dokploy/components/dashboard/application/advanced/redirects/add-redirect.tsx
apps/dokploy/components/dashboard/application/advanced/redirects/update-redirect.tsx
apps/dokploy/components/dashboard/application/advanced/security/add-security.tsx
apps/dokploy/components/dashboard/application/advanced/security/update-security.tsx
apps/dokploy/components/dashboard/application/advanced/volumes/add-volumes.tsx
apps/dokploy/components/dashboard/application/advanced/volumes/update-volume.tsx
apps/dokploy/components/dashboard/application/update-application.tsx
apps/dokploy/components/dashboard/compose/update-compose.tsx
apps/dokploy/components/dashboard/database/backups/update-backup.tsx
apps/dokploy/components/dashboard/mongo/update-mongo.tsx
apps/dokploy/components/dashboard/postgres/update-postgres.tsx
apps/dokploy/components/dashboard/projects/update.tsx
apps/dokploy/components/dashboard/settings/destination/update-destination.tsx
apps/dokploy/components/dashboard/settings/notifications/update-notification.tsx

refactor: add dialog close on submit success

---

apps/dokploy/components/dashboard/settings/cluster/nodes/manager/add-manager.tsx
apps/dokploy/components/dashboard/settings/cluster/nodes/workers/add-worker.tsx
apps/dokploy/server/api/routers/cluster.ts

Adds the current version of Docker dynamically to the Docker installation command to prevent compatibility issues on other Docker Swarm nodes.

fix: wrong Docker version in Add Node commands

---

apps/dokploy/components/dashboard/settings/web-server.tsx
apps/dokploy/components/dashboard/settings/web-server/edit-traefik-env.tsx
apps/dokploy/server/api/routers/settings.ts
apps/dokploy/server/setup/traefik-setup.ts

31 are there any plans to support wildcard dns records

---

apps/dokploy/templates/documenso/docker-compose.yml

fix(documenso): add version

---

apps/dokploy/server/setup/traefik-setup.ts

feat(traefik): upgrade traefik to v.3.1.2

---

apps/dokploy/components/dashboard/compose/monitoring/show.tsx
apps/dokploy/server/api/routers/docker.ts
apps/dokploy/server/api/services/docker.ts

https://github.com/Dokploy/dokploy/issues/411

feat: added restart button for containers

---

apps/docs/content/docs/core/templates/overview.cn.mdx
apps/docs/content/docs/core/templates/overview.mdx

Just removed few duplicates in the examples page

docs: removed duplicates from examples

---

apps/dokploy/components/dashboard/projects/show.tsx

fix: add missing compose .length #433

---

apps/dokploy/components/dashboard/project/add-template.tsx

The UI speaks of deploying a template while actually it's _creating_ a new application from a template and _adding_ it to the project. I fixed some of the language to better reflect what it does.

Corrected language for creating applications from a template

---

apps/dokploy/components/dashboard/application/advanced/cluster/show-cluster-settings.tsx
apps/dokploy/package.json
apps/dokploy/server/api/routers/settings.ts

439 unable to open swagger

---

apps/dokploy/components/dashboard/project/add-application.tsx
apps/dokploy/components/dashboard/project/add-compose.tsx
apps/dokploy/components/dashboard/project/add-database.tsx

I've added similar code for add-application, add-compose and add-database. It might be a good candidate for some generic code which I'll leave up to the maintainer to decide.

Generate valid appName on changing name

---

apps/dokploy/server/utils/builders/nixpacks.ts

fix(nixpacks): adjust build path on nixpacks static

---

apps/dokploy/components/dashboard/settings/servers/add-server.tsx
apps/dokploy/components/dashboard/settings/servers/update-server.tsx
apps/dokploy/package.json

fix(multi-server): remove string validation on port

---

apps/dokploy/components/dashboard/mariadb/general/show-external-mariadb-credentials.tsx
apps/dokploy/components/dashboard/mongo/general/show-external-mongo-credentials.tsx
apps/dokploy/components/dashboard/mysql/general/show-external-mysql-credentials.tsx
apps/dokploy/components/dashboard/postgres/general/show-external-postgres-credentials.tsx
apps/dokploy/components/dashboard/project/add-compose.tsx
apps/dokploy/components/dashboard/redis/general/show-external-redis-credentials.tsx

509 create compose modal remains open after clicking create

---

apps/dokploy/server/api/routers/destination.ts

fix(destinations): change admin to protected procedure

---

apps/dokploy/server/utils/providers/bitbucket.ts
apps/dokploy/server/utils/providers/github.ts
apps/dokploy/server/utils/providers/gitlab.ts
apps/dokploy/server/utils/providers/raw.ts

fix(compose): delete content when is remote server

---

apps/dokploy/components/dashboard/settings/cluster/registry/add-docker-registry.tsx
apps/dokploy/components/dashboard/settings/cluster/registry/update-docker-registry.tsx
apps/dokploy/drizzle/0038_rapid_landau.sql
apps/dokploy/drizzle/meta/0038_snapshot.json
apps/dokploy/drizzle/meta/_journal.json
apps/dokploy/server/api/routers/registry.ts
apps/dokploy/server/api/services/registry.ts
apps/dokploy/server/db/schema/registry.ts

fix(registry): add option to login the registry in the remote server

---

apps/dokploy/server/utils/providers/bitbucket.ts

Increase the `pagelen` param 100 (maximum), default is 10.

fix: bitbucket repositories length

---

apps/dokploy/components/dashboard/projects/show.tsx
apps/dokploy/server/api/routers/project.ts

In case the project has only one domain, the icon will be a simple link.

feat: add dropdown link

---

apps/dokploy/components/dashboard/application/advanced/show-application-advanced-settings.tsx
apps/dokploy/components/dashboard/application/domains/show-domains.tsx
apps/dokploy/components/dashboard/compose/domains/show-domains.tsx
apps/dokploy/components/dashboard/mariadb/advanced/show-mariadb-resources.tsx
apps/dokploy/components/dashboard/mariadb/backups/show-backup-mariadb.tsx
apps/dokploy/components/dashboard/mongo/advanced/show-mongo-resources.tsx
apps/dokploy/components/dashboard/mongo/backups/show-backup-mongo.tsx
apps/dokploy/components/dashboard/mongo/volumes/show-volumes.tsx
apps/dokploy/components/dashboard/monitoring/docker/show.tsx
apps/dokploy/components/dashboard/mysql/advanced/show-mysql-resources.tsx
apps/dokploy/components/dashboard/mysql/backups/show-backup-mysql.tsx
apps/dokploy/components/dashboard/postgres/advanced/show-postgres-resources.tsx
apps/dokploy/components/dashboard/postgres/backups/show-backup-postgres.tsx
apps/dokploy/components/dashboard/redis/advanced/show-redis-resources.tsx
apps/dokploy/components/dashboard/settings/certificates/show-certificates.tsx
apps/dokploy/components/dashboard/settings/cluster/registry/show-registry.tsx
apps/dokploy/components/dashboard/settings/destination/show-destinations.tsx
apps/dokploy/components/dashboard/settings/notifications/show-notifications.tsx
apps/dokploy/components/dashboard/settings/profile/profile-form.tsx
apps/dokploy/components/dashboard/settings/web-domain.tsx

This fixes a bunch of grammer and typo errors in the project to make things easier to read and understand.

Fix typos and grammar errors

---

apps/dokploy/components/dashboard/settings/certificates/add-certificate.tsx
apps/dokploy/components/layouts/settings-layout.tsx
apps/dokploy/drizzle/0040_graceful_wolfsbane.sql
apps/dokploy/drizzle/meta/0040_snapshot.json
apps/dokploy/drizzle/meta/_journal.json
apps/dokploy/server/api/routers/certificate.ts
packages/server/src/db/schema/admin.ts
packages/server/src/db/schema/certificate.ts
packages/server/src/db/schema/server.ts
packages/server/src/services/certificate.ts

feat(certificates): create certificates in a remote server

---

packages/server/src/utils/providers/bitbucket.ts
packages/server/src/utils/providers/git.ts
packages/server/src/utils/providers/github.ts
packages/server/src/utils/providers/gitlab.ts

feat(dokploy): add recurse submodules to providers #331

---

apps/dokploy/templates/directus/index.ts
apps/website/public/canary.sh
apps/website/public/feature.sh
apps/website/public/install.sh

fix(installation): exit of script when docker swarm init fails

---

apps/dokploy/reset-password.ts

fix(dokploy): use the exact path of functions #578

---

apps/dokploy/package.json
packages/server/src/utils/backups/mongo.ts

fix(dokploy): add missing --archive to mongodump

---

packages/server/src/setup/postgres-setup.ts
packages/server/src/setup/redis-setup.ts

fix(dokploy): remove expose ports in production

---

apps/dokploy/components/dashboard/settings/billing/show-billing.tsx

fix(dokploy): adjust dark and light mode billing

---

apps/dokploy/components/dashboard/settings/billing/show-billing.tsx
apps/dokploy/migration.ts
apps/dokploy/pages/api/stripe/webhook.ts
apps/dokploy/server/api/routers/auth.ts
apps/dokploy/server/api/routers/stripe.ts
apps/dokploy/server/db/drizzle.config.ts
apps/dokploy/server/db/index.ts
apps/dokploy/server/db/migration.ts
apps/dokploy/server/db/reset.ts
apps/dokploy/server/db/seed.ts
apps/dokploy/server/utils/stripe.ts
apps/schedules/src/queue.ts
packages/server/src/db/drizzle.config.ts
packages/server/src/db/index.ts
packages/server/src/db/migration.ts
packages/server/src/db/reset.ts
packages/server/src/db/seed.ts
packages/server/src/emails/emails/notion-magic-link.tsx
packages/server/src/emails/emails/plaid-verify-identity.tsx
packages/server/src/emails/emails/stripe-welcome.tsx
packages/server/src/emails/emails/vercel-invite-user.tsx
packages/server/src/setup/traefik-setup.ts

This syntax is smaller and more readable, it also helps clean up some if checks here and there.

Switch to use ! syntax instead of || ""

---

apps/dokploy/components/dashboard/docker/logs/docker-logs-id.tsx
apps/dokploy/server/wss/docker-container-logs.ts

fix(dokploy): prevent to have pending connections docker logs

---

apps/dokploy/components/dashboard/project/add-template.tsx

This PR introduces the following changes to enhance the user interface:
1. **Document Icon**: Added an icon to indicate documentation links, making it easier for users to identify and access relevant documentation.
2. **Line Clamp**: Implemented `lineclamp-3` to limit the display of extra text that was breaking the UI. This improves the overall layout and user experience by ensuring that text remains within a defined space.
- Added a document icon to relevant sections.
- Applied `lineclamp-3` CSS class to text elements to prevent extra text and maintain UI integrity.

style(ui): update template selection view

---

packages/server/src/utils/providers/bitbucket.ts

fix(dokploy): extract all the repositories bitbucket #619

---

apps/dokploy/server/api/routers/project.ts

refactor(dokploy): add missing project

---

packages/server/src/utils/docker/domain.ts

fix: domain path ignored in compose services

---

apps/dokploy/components/dashboard/settings/servers/actions/toggle-docker-cleanup.tsx

fix(dokploy): sync the toggle value when enable docker cleanup #651

---

packages/server/src/services/mongo.ts

The application name for mongodb was wrong. This commit changes it.

fix: mongodb app naming

---

apps/dokploy/__test__/compose/domain/labels.test.ts
apps/dokploy/package.json
packages/server/src/utils/docker/domain.ts

fix(compose): add path prefix inside Host rule

---

apps/dokploy/components/dashboard/application/advanced/redirects/add-redirect.tsx

fix(dokploy): remove $ on presets redirect

---

apps/dokploy/server/api/routers/compose.ts

when calling the compose create api, a empty result was returned

fix compose.create not returning result

---

apps/dokploy/components/icons/data-tools-icons.tsx
apps/dokploy/pages/dashboard/projects.tsx

fix: prevent to load stripe code when is not cloud

---

apps/dokploy/components/dashboard/application/general/generic/save-docker-provider.tsx
apps/dokploy/drizzle/0046_purple_sleeper.sql
apps/dokploy/drizzle/meta/0046_snapshot.json
apps/dokploy/drizzle/meta/_journal.json
apps/dokploy/server/api/routers/application.ts
packages/server/src/db/schema/application.ts
packages/server/src/services/application.ts
packages/server/src/utils/docker/utils.ts
packages/server/src/utils/providers/docker.ts
packages/server/src/utils/providers/github.ts

fix: add registry url and use spawnAsync

---

packages/server/src/emails/emails/build-failed.tsx
packages/server/src/emails/emails/build-success.tsx
packages/server/src/emails/emails/database-backup.tsx
packages/server/src/emails/emails/docker-cleanup.tsx
packages/server/src/emails/emails/dokploy-restart.tsx
packages/server/src/emails/emails/invitation.tsx

fix: update img url

---

apps/dokploy/pages/api/deploy/github.ts

fix: allow multiple repositories from same name github #690

---

apps/dokploy/components/dashboard/application/general/show.tsx
apps/dokploy/components/dashboard/compose/general/actions.tsx
apps/dokploy/components/ui/switch.tsx

style: added autodeploy switch

---

apps/dokploy/components/dashboard/compose/general/actions.tsx
apps/dokploy/components/dashboard/compose/start-compose.tsx
apps/dokploy/components/dashboard/compose/stop-compose.tsx
apps/dokploy/pages/api/deploy/github.ts
apps/dokploy/server/api/routers/compose.ts
packages/server/src/services/compose.ts

Previously, stop docker-compose button was broken, and there was and there was no start option. This PR ensures that docker-compose stop works, and additionally introduces for starting docker-compose.
- Fixed the stop button.
- Added start `docker-compose` option.
https://github.com/user-attachments/assets/921da94a-4f80-4b3e-8e8b-068c3557d180

fix/feat: fixed stop compose & added start compose

---

apps/dokploy/templates/templates.ts
apps/dokploy/templates/umami/docker-compose.yml

This pull request includes updates to the Umami template.

Feat<templates>:Updated Umami to v2.14.0

---

apps/dokploy/components/dashboard/docker/terminal/docker-terminal-modal.tsx
apps/dokploy/components/dashboard/settings/web-server/docker-terminal-modal.tsx

https://github.com/Dokploy/dokploy/issues/818

feat: add prevent dialog when leaving a terminal

---

apps/dokploy/components/dashboard/application/advanced/volumes/update-volume.tsx

fix: show mount path when is not compose

---

Dockerfile
Dockerfile.cloud
apps/dokploy/components/dashboard/application/advanced/volumes/add-volumes.tsx
apps/dokploy/components/dashboard/application/advanced/volumes/update-volume.tsx

refactor: add code editor in volumes edit

---

packages/server/src/utils/gpu-setup.ts

- Replace pkexec with sudo for better compatibility
- Improve error message to guide users about sudo privileges

fix: update GPU setup command to use sudo and add error handling

---

apps/dokploy/pages/api/providers/gitlab/callback.ts
apps/dokploy/server/api/routers/gitlab.ts
packages/server/src/utils/providers/gitlab.ts

Tested the connection to a self hosted gitlab enterprise and fixed everything so that gitlab apps will deploy

560 self hosted gitlab additions

---

.gitignore
.vscode/extensions.json
.vscode/settings.json

Added settings.json to use biome.js formatter by default 
Added extentions.json to recommend to install biome.js
This all is to keep spacing the same across different contributors and to make it easier for people to get started contributing

format: setup .vscode folder with biome.js for consistent format and spacing

---

apps/dokploy/components/dashboard/settings/servers/gpu-support.tsx
apps/dokploy/components/dashboard/settings/servers/validate-server.tsx
packages/server/src/setup/server-setup.ts
packages/server/src/setup/server-validate.ts

When setting up on ARM-based servers (like ARM VPS instances at Hetzner), the validation step fails with a JSON parsing error. This occurred because buildpacks was attempting to install x86 binaries on ARM architecture.

fix(setup/validate): arm64 build fixes, improved validation

---

apps/dokploy/pages/dashboard/project/[projectId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/application/[applicationId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/compose/[composeId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/mariadb/[mariadbId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/mongo/[mongoId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/mysql/[mysqlId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/postgres/[postgresId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/redis/[redisId].tsx

Project: Vandelay Industries | Dokploy
Compose: pocketbase - Vandelay Industries | Dokploy
Application: frontend - Vandelay Industries | Dokploy
Database: db - Vandelay Industries | Dokploy

chore: clean up page titles

---

apps/dokploy/components/dashboard/docker/logs/terminal-line.tsx
apps/dokploy/components/dashboard/docker/logs/utils.ts

This pull request enhances the `TerminalLine` component by adding ANSI color code parsing and improving the message highlighting logic. The most important changes include the addition of the `parseAnsi` function and modifications to the `highlightMessage` function to support ANSI color codes.
Enhancements to `TerminalLine` component:
* [`apps/dokploy/components/dashboard/docker/logs/terminal-line.tsx`](diffhunk://#diff-219a675bf21dd72a836467a41488fb5c123d565c76981e5397529b1730eca434L12-R12): Imported `parseAnsi` from `./utils` to handle ANSI color codes.
* [`apps/dokploy/components/dashboard/docker/logs/terminal-line.tsx`](diffhunk://#diff-219a675bf21dd72a836467a41488fb5c123d565c76981e5397529b1730eca434L36-R67): Updated the `highlightMessage` function to parse ANSI color codes and handle …

feat(logs): support ansi codes

---

apps/dokploy/components/dashboard/docker/terminal/docker-terminal.tsx
apps/dokploy/components/dashboard/settings/web-server/terminal.tsx

fix(term): fix light mode foreground color

---

packages/server/src/utils/builders/index.ts
packages/server/src/utils/cluster/upload.ts
packages/server/src/utils/providers/docker.ts

fix(docker): fix for custom registry login

---

apps/dokploy/templates/plausible/docker-compose.yml
apps/dokploy/templates/templates.ts

Bumps plausible to v2.1.4 again, this was done before but somehow reverted.

feat(plausible): bump to 2.1.4

---

apps/dokploy/components/dashboard/settings/certificates/show-certificates.tsx

This PR adds certificate expiration date and chain details to the Certificates page.

feat(certs): show expiration and chain details

---

apps/dokploy/server/api/routers/settings.ts
packages/server/src/utils/backups/index.ts

fix: add missing notifications in cron jobs

---

apps/dokploy/components/dashboard/settings/notifications/show-notifications.tsx
apps/dokploy/components/dashboard/settings/notifications/update-notification.tsx

style(notifications): fixed white style

---

apps/dokploy/components/dashboard/application/deployments/show-deployment.tsx
apps/dokploy/components/dashboard/compose/deployments/show-deployment-compose.tsx

feat: add hide extra logs

---

packages/server/src/setup/server-setup.ts

[#15](https://github.com/Dokploy/website/issues/15)

refactor: add fallback ipv4

---

apps/dokploy/components/dashboard/application/environment/show.tsx

style: environment style improvement

---

apps/dokploy/templates/templates.ts
apps/dokploy/templates/vaultwarden/docker-compose.yml

Update version of template 1.32.3 to 1.32.7 for fix CVE.
https://github.com/dani-garcia/vaultwarden/releases/tag/1.32.7

fix: Update Vaultwarden version to 1.32.7 [CVE fix]

---

apps/dokploy/templates/wordpress/docker-compose.yml

Thank you for the excellent project.
I have updated the WordPress template Docker image version to the latest.

Update wordpress version to latest

---

apps/dokploy/pages/_document.tsx

fix(ui): full width for body tag

---

apps/dokploy/components/layouts/side.tsx
apps/dokploy/components/ui/modeToggle.tsx

Logo needs a fix doesn't look good when collapsed

refactor: add theme toggle and language selection to user navigation

---

apps/dokploy/pages/dashboard/project/[projectId]/services/mongo/[mongoId].tsx

fix: db type typo

---

apps/dokploy/components/dashboard/project/add-template.tsx

style: fix tablet and mobile (Create from Template)

---

apps/dokploy/styles/globals.css

feat(style): custom scrollbar styling

---

apps/dokploy/__test__/deploy/github.test.ts
apps/dokploy/__test__/vitest.config.ts
apps/dokploy/pages/api/deploy/github.ts

skip deploy by commit message, follow https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/skipping-workflow-runs

feat: add ci skip check

---

apps/dokploy/components/dashboard/docker/logs/utils.ts

chore(logs): update utils.ts

---

apps/dokploy/templates/teable/docker-compose.yml

The Alpha version was causing database errors, but the latest version seems to have resolved these issues. Therefore, I am creating this PR.

fix: teable template

---

apps/dokploy/components/dashboard/monitoring/docker/docker-block-chart.tsx
apps/dokploy/components/dashboard/monitoring/docker/docker-cpu-chart.tsx
apps/dokploy/components/dashboard/monitoring/docker/docker-memory-chart.tsx
apps/dokploy/components/dashboard/monitoring/docker/docker-network-chart.tsx
apps/dokploy/components/dashboard/monitoring/docker/show.tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/application/[applicationId].tsx
apps/dokploy/pages/dashboard/project/[projectId]/services/compose/[composeId].tsx
apps/dokploy/server/wss/docker-stats.ts
packages/server/src/index.ts
packages/server/src/monitoring/utils.ts
packages/server/src/services/application.ts

refactor: update docker stats

---

packages/server/src/services/application.ts

Please review my PR, it's the first time I explore the code.

Fix deploy env variable URL : should be a string, not an object

---

apps/dokploy/templates/plausible/docker-compose.yml
apps/dokploy/templates/templates.ts

Updates plausible to the newest version also remove the version from the top since that isnt used anymore.

feat(template): update plausible

---

apps/dokploy/components/dashboard/monitoring/free/container/show-free-compose-monitoring.tsx
apps/dokploy/components/dashboard/monitoring/paid/container/show-paid-compose-monitoring.tsx
apps/dokploy/pages/dashboard/project/[projectId].tsx

style(monitoring): use status badges for compose monitoring

---

apps/dokploy/templates/listmonk/docker-compose.yml

this is required in the compose file for listmonk to function properly for file uploads

fix(templates): listmonk needed files volumes

---

apps/dokploy/components/dashboard/application/deployments/show-deployments.tsx
packages/server/src/services/deployment.ts

- Add deployment index numbering in the UI
- Adjust deployment cleanup to retain 9 instead of 10 deployments
- Update deployment list rendering to show numbered status

feat(deployments): improve deployment list display and cleanup logic

---

apps/dokploy/templates/zipline/docker-compose.yml

feat(zipline): update zipline version

---

apps/dokploy/templates/superset/docker-compose.yml

fix(template): superset

---

apps/dokploy/components/dashboard/settings/handle-ai.tsx
apps/dokploy/server/api/routers/ai.ts
packages/server/src/services/ai.ts
packages/server/src/utils/ai/select-ai-provider.ts

feat: fallback to openai compatible provider if url host doesn't match

---

apps/dokploy/__test__/traefik/server/update-server-config.test.ts
apps/dokploy/components/dashboard/requests/request-distribution-chart.tsx
apps/dokploy/components/dashboard/requests/requests-table.tsx
apps/dokploy/components/dashboard/requests/show-requests.tsx
apps/dokploy/components/ui/calendar.tsx
apps/dokploy/drizzle/0071_flaky_black_queen.sql
apps/dokploy/drizzle/meta/0071_snapshot.json
apps/dokploy/drizzle/meta/_journal.json
apps/dokploy/server/api/routers/settings.ts
packages/server/src/db/schema/user.ts
packages/server/src/index.ts
packages/server/src/utils/access-log/handler.ts
packages/server/src/utils/access-log/utils.ts
packages/server/src/utils/backups/index.ts
packages/server/src/utils/traefik/application.ts
pnpm-lock.yaml

- Implement date range filtering for access logs and request statistics
- Add log cleanup scheduling with configurable cron expression
- Update UI components to support date range selection
- Refactor log processing and parsing to handle date filtering
- Add new database migration for log cleanup cron configuration
- Remove deprecated log rotation management logic

feat(monitoring): add date range filtering and log cleanup scheduling

---

packages/server/src/services/docker.ts

- Add sorting to container retrieval methods in docker service
- Ensure consistent container list ordering across different container fetching functions
- Improve readability and predictability of container list results

refactor(docker): sort container lists by name

---

apps/dokploy/components/dashboard/application/environment/show-enviroment.tsx

- Adjust CodeEditor component wrapper and class names
- Enhance font and styling for environment configuration
- Optimize form item and control rendering

refactor(ui): improve environment code editor styling and layout

---

apps/dokploy/pages/dashboard/project/[projectId].tsx
apps/dokploy/server/api/routers/application.ts
apps/dokploy/server/api/routers/compose.ts
apps/dokploy/server/api/routers/mariadb.ts
apps/dokploy/server/api/routers/mongo.ts
apps/dokploy/server/api/routers/mysql.ts
apps/dokploy/server/api/routers/postgres.ts
apps/dokploy/server/api/routers/redis.ts

- Implement service move feature for applications, compose, databases, and other services
- Add move dialog with project selection for bulk service transfer
- Create move mutation endpoints for each service type
- Enhance project management with cross-project service relocation
- Improve user experience with error handling and success notifications

feat(services): add bulk service move functionality across projects

---

apps/dokploy/pages/dashboard/project/[projectId].tsx

- Implement bulk delete feature for applications, compose, and various database services
- Add delete mutation endpoints for each service type
- Provide user-friendly bulk delete action with error handling and success notifications
- Integrate Trash2 icon for delete action in bulk service management

feat(services): add bulk delete functionality for services

---

apps/dokploy/components/dashboard/application/environment/show-enviroment.tsx
apps/dokploy/components/dashboard/application/environment/show.tsx

- Implement form change tracking for environment variables
- Add cancel and save buttons with conditional rendering
- Disable save button when no changes are detected
- Show unsaved changes warning in description
- Improve user experience with form state management

feat(environment): add unsaved changes handling for environment settings

---

apps/dokploy/pages/dashboard/project/[projectId].tsx

Sorting created at order fix
Before/After:
Newest first
Oldest first

fix(ui): sorting

---

apps/dokploy/components/dashboard/projects/show.tsx
apps/dokploy/tailwind.config.ts

Add support for large screens >1920px / 120rem
Five columns on projects page

fix(ui): projects layout

---

apps/dokploy/components/dashboard/application/general/show.tsx
apps/dokploy/components/dashboard/compose/general/actions.tsx
apps/dokploy/components/dashboard/mariadb/general/show-external-mariadb-credentials.tsx
apps/dokploy/components/dashboard/mariadb/general/show-general-mariadb.tsx
apps/dokploy/components/dashboard/mongo/general/show-external-mongo-credentials.tsx
apps/dokploy/components/dashboard/mongo/general/show-general-mongo.tsx
apps/dokploy/components/dashboard/mysql/general/show-external-mysql-credentials.tsx
apps/dokploy/components/dashboard/mysql/general/show-general-mysql.tsx
apps/dokploy/components/dashboard/postgres/general/show-external-postgres-credentials.tsx
apps/dokploy/components/dashboard/postgres/general/show-general-postgres.tsx
apps/dokploy/components/dashboard/postgres/general/show-internal-postgres-credentials.tsx
apps/dokploy/components/dashboard/postgres/update-postgres.tsx
apps/dokploy/components/dashboard/redis/general/show-external-redis-credentials.tsx
apps/dokploy/components/dashboard/redis/general/show-general-redis.tsx

Ensures consistent styling and functionality across all database-related components, including PostgreSQL, MongoDB, MySQL, Redis, and MariaDB. Changes include:
- **Icon Placement**: Moved all icons to the left of button text for better visual hierarchy.
- **Tooltip Wrapping**: Removed HelpCircle (question mark) icons and wrapped tooltips directly around buttons. Tooltips now appear when hovering over the button itself.
- **Accessibility Enhancements**:
- Added focus indicators (`focus-visible:ring-2 focus-visible:ring-offset-2`) for better keyboard navigation.
- Improved spacing and alignment for all buttons.
- **Button Layout**:
- Added consistent spacing (`mr-1`) between icons and text.
- Ensured uniform styling for similar actions across all database components.
- **Icons**:
- Added …

Fix: Consistent Component Styling and Server URL

---

apps/dokploy/components/dashboard/mongo/general/show-general-mongo.tsx

…omponent
- Standardized indentation and formatting for better readability.
- Enhanced tooltip integration within button elements for improved user experience.
- Maintained functionality for deploying, reloading, starting, and stopping MongoDB instances while ensuring consistent code style.

Fix: move buttons to allow deploy, rebuild etc in mongodb

---

packages/server/src/utils/docker/domain.ts

Fixed network search in Traefik Labels for the service

---

apps/dokploy/server/api/routers/ai.ts
apps/dokploy/server/api/routers/application.ts
apps/dokploy/server/api/routers/compose.ts
apps/dokploy/server/api/routers/mariadb.ts
apps/dokploy/server/api/routers/mongo.ts
apps/dokploy/server/api/routers/mysql.ts
apps/dokploy/server/api/routers/organization.ts
apps/dokploy/server/api/routers/postgres.ts
apps/dokploy/server/api/routers/project.ts
apps/dokploy/server/api/routers/redis.ts
apps/dokploy/server/api/routers/settings.ts
apps/dokploy/server/api/trpc.ts

- Updated the user role property from `rol` to `role` across multiple TRPC context and router files to ensure consistency and clarity in role management.
- Adjusted conditional checks for user roles in various procedures to reflect the updated property name, enhancing code readability and maintainability.

Refactor user role handling in TRPC context and routers

---

apps/dokploy/components/dashboard/docker/logs/docker-logs-id.tsx

https://github.com/Dokploy/dokploy/issues/1815

limit rawLogs to max number of lines by trimming old entries

---

apps/dokploy/components/dashboard/project/add-application.tsx
apps/dokploy/components/dashboard/project/add-compose.tsx
apps/dokploy/components/dashboard/project/add-database.tsx
apps/dokploy/components/dashboard/projects/handle-project.tsx
apps/dokploy/lib/slug.ts

- Updated the appName generation logic in `AddApplication`, `AddCompose`, and `AddDatabase` components to use the `slugify` function for improved consistency and readability.
- Enhanced the `slugify` function to return a default value of "service" if the input is empty, ensuring robustness in name generation.
- Improved project name validation in `handle-project.tsx` to enforce stricter rules on naming conventions.

Refactor appName generation in dashboard components

---

apps/dokploy/components/dashboard/application/general/generic/save-gitea-provider.tsx
packages/server/src/utils/providers/gitea.ts

- Updated the `testGiteaConnection` and `getGiteaRepositories` functions to implement pagination when fetching repositories from the Gitea API, ensuring all repositories are retrieved.
- Enhanced error handling for API responses and improved the structure of the returned repository data.
- Removed deprecated code related to direct repository fetching, streamlining the overall logic.

Refactor Gitea repository fetching to handle pagination

---

packages/server/src/utils/backups/utils.ts

fix: use root password instead of user one

---

Dockerfile
packages/server/src/setup/server-setup.ts
packages/server/src/utils/builders/railpack.ts

Hi, I need this version to build my deno app.
What's the fastest way to make this version change possible for me?
https://github.com/railwayapp/railpack/releases/tag/v0.0.64

update railpack to 0.0.64

---

packages/server/src/utils/builders/compose.ts

fix: update Docker network creation command to support overlay driver in docker stack deployments

---

apps/dokploy/pages/_error.tsx

fix: Submit Log in issue on Github

---

Dockerfile
packages/server/src/setup/server-setup.ts

The latest versions of nixpacks include fixes for react-router v7: https://github.com/railwayapp/nixpacks/pull/1303

build: update nixpacks to 1.39.0

---

packages/server/src/utils/backups/web-server.ts

fix: update rsync command in web server backup to remove verbose flag

---

apps/dokploy/components/dashboard/compose/general/isolated-deployment.tsx
apps/dokploy/components/dashboard/compose/general/randomize-compose.tsx

Resolves #1916
[output.webm](https://github.com/user-attachments/assets/3078cca1-1136-4b6e-8955-3d06fd6e3c14)

fix: multiple notifications for isolated compose and randomize compose

---

apps/dokploy/components/dashboard/projects/handle-project.tsx

fix: allow dot character in project name validation (#2042)

---

packages/server/src/utils/backups/compose.ts
packages/server/src/utils/backups/mariadb.ts
packages/server/src/utils/backups/mongo.ts
packages/server/src/utils/backups/mysql.ts
packages/server/src/utils/backups/postgres.ts
packages/server/src/utils/notifications/database-backup.ts

- Add database name information in database backup notification

feat: add database name in database backup notification

---

apps/dokploy/components/dashboard/settings/cluster/nodes/show-nodes.tsx
apps/dokploy/components/dashboard/settings/servers/show-servers.tsx

style: Remove the width restriction on the server name.

---

apps/dokploy/components/ui/popover.tsx
apps/dokploy/styles/globals.css

The current code editor style only applies the mono font settings of the editor itself. Now that Tailwind has been introduced, I think embedding the Tailwind mono font settings will provide a better UI experience.

Style: Make all code editors apply Tailwind CSS font-mono style.

---

GUIDES.md

Update Ubuntu Docker installation instructions in [`GUIDES.md`](https://github.com/Dokploy/dokploy/blob/canary/GUIDES.md) following [official installation methods](https://docs.docker.com/engine/install/ubuntu/) to improve cleanup, key management, repository setup, and plugin installation.
Documentation:
- Add removal of old Docker and related packages before installation
- Simplify prerequisites installation and create /etc/apt/keyrings for storing keys
- Store Docker GPG key in /etc/apt/keyrings/docker.asc with appropriate permissions
- Use dynamic architecture detection and Ubuntu codename from /etc/os-release when configuring the Docker Apt repository
- Include Docker Buildx and Compose plugins in the installation step

docs: update docker installation method of Ubuntu

---

apps/dokploy/components/dashboard/swarm/applications/show-applications.tsx

Style: Change Node Applications dialog width, more easy to read.

---

apps/dokploy/server/api/routers/application.ts

- Eliminated the conditional logic for stopping services based on serverId, streamlining the application status update process.
- This change enhances code clarity and maintains focus on application state management.

refactor(application): remove redundant service stop logic

---

packages/server/src/db/schema/rollbacks.ts
packages/server/src/services/rollbacks.ts
packages/server/src/utils/builders/index.ts

…port
- Updated the rollbacks schema to include mounts, ports, and optional registry information in the full context.
- Refactored the rollback service to utilize the full context for improved rollback operations, ensuring all necessary configurations are applied.
- Exported the getAuthConfig function for better accessibility in the application context.

fix(rollbacks): correct dns issue resolution

---

packages/server/src/utils/docker/utils.ts

fix: fix environment variable parsing for railpack

---

packages/server/src/setup/traefik-setup.ts

Some config changes:
- Disable send anonymous usage (https://doc.traefik.io/traefik/contributing/data-collection/)
- Add access log path (https://doc.traefik.io/traefik/observability/access-logs/)
accessLog filePath also for fix missing access.log:

feat(config): Traefik

---

apps/dokploy/components/dashboard/settings/git/github/add-github-provider.tsx

appended a 5-char random string to the name creation, as to prevent conflicts with other existing Dokploy GitHub apps.
Issue I created was at: https://github.com/Dokploy/dokploy/issues/2265. Not sure if it was a "fix" per se.

fix: github app creation name conflicting with already existing Dokploy names

---

apps/dokploy/__test__/compose/compose.test.ts
apps/dokploy/__test__/compose/config/config-root.test.ts
apps/dokploy/__test__/compose/config/config-service.test.ts
apps/dokploy/__test__/compose/config/config.test.ts
apps/dokploy/__test__/compose/network/network-root.test.ts
apps/dokploy/__test__/compose/network/network-service.test.ts
apps/dokploy/__test__/compose/network/network.test.ts
apps/dokploy/__test__/compose/secrets/secret-root.test.ts
apps/dokploy/__test__/compose/secrets/secret-services.test.ts
apps/dokploy/__test__/compose/secrets/secret.test.ts
apps/dokploy/__test__/compose/service/service-container-name.test.ts
apps/dokploy/__test__/compose/service/service-depends-on.test.ts
apps/dokploy/__test__/compose/service/service-extends.test.ts
apps/dokploy/__test__/compose/service/service-links.test.ts
apps/dokploy/__test__/compose/service/service-names.test.ts
apps/dokploy/__test__/compose/service/service.test.ts
apps/dokploy/__test__/compose/service/sevice-volumes-from.test.ts
apps/dokploy/__test__/compose/volume/volume-2.test.ts
apps/dokploy/__test__/compose/volume/volume-root.test.ts
apps/dokploy/__test__/compose/volume/volume-services.test.ts
apps/dokploy/__test__/compose/volume/volume.test.ts
apps/dokploy/__test__/deploy/github.test.ts
apps/dokploy/__test__/drop/drop.test.ts
apps/dokploy/__test__/requests/request.test.ts
apps/dokploy/__test__/traefik/traefik.test.ts

Enhancements:
- Refactor test files in [apps/dokploy/\_\_test\_\_](https://github.com/Dokploy/dokploy/tree/canary/apps/dokploy/__test__) to meet linting standards
```sh
pnpm check apps/dokploy/__test__
```

refactor: lint apps/docker/__test__ files

---

README.md

Polish [README.md](https://github.com/Dokploy/dokploy/blob/canary/README.md) by enhancing section headings with emojis, cleaning up HTML attributes, and improving image accessibility.
You can [see the preview](https://github.com/JamBalaya56562/dokploy/blob/readme/README.md).
Documentation:
- Add emojis and adjust heading levels for Features, Sponsors, Video Tutorial, and Contributing sections
- Remove redundant HTML attributes from logos and images to simplify markup
- Add missing alt text to contributor image for accessibility

docs: polish `README.md`

---

apps/dokploy/components/dashboard/application/domains/handle-domain.tsx
biome.json

feat(dashboard): add manual input for service name in domains for docker compose

---

apps/dokploy/components/dashboard/docker/logs/docker-logs-id.tsx

feat(docker-logs): add pause/resume functionality for log streaming

---

apps/dokploy/components/layouts/dashboard-layout.tsx
apps/dokploy/server/api/routers/settings.ts

Please describe in a short paragraph what this PR is about.
Close automatically the related issues using the keywords: `closes #ISSUE_NUMBER`, `fixes #ISSUE_NUMBER`, `resolves #ISSUE_NUMBER`
Example: `closes #123`
If you include a video or screenshot, would be awesome so we can see the changes in action.

feat(settings): add user subscription check to dashboard layout

---

apps/dokploy/components/dashboard/application/deployments/show-deployments.tsx
apps/dokploy/components/dashboard/application/schedules/show-schedules.tsx

Please describe in a short paragraph what this PR is about.
[before.webm](https://github.com/user-attachments/assets/93190126-3ba6-47d3-afb1-c6009143738d)
[after.webm](https://github.com/user-attachments/assets/8373defb-f532-4b0d-a462-d113154f3eb7)

fix(ui): schedule responsiveness

---

apps/dokploy/components/dashboard/mariadb/general/show-external-mariadb-credentials.tsx
apps/dokploy/components/dashboard/mongo/general/show-external-mongo-credentials.tsx
apps/dokploy/components/dashboard/mysql/general/show-external-mysql-credentials.tsx
apps/dokploy/components/dashboard/postgres/general/show-external-postgres-credentials.tsx
apps/dokploy/components/dashboard/redis/general/show-external-redis-credentials.tsx

fix: typo and improve grammar

---

apps/dokploy/components/dashboard/settings/profile/profile-form.tsx
apps/dokploy/server/api/routers/user.ts
packages/server/src/db/schema/user.ts
packages/server/src/services/user.ts

Fix profile email validation to prevent empty values causing sign-in issues-#2613

---

apps/dokploy/components/shared/status-tooltip.tsx
apps/dokploy/drizzle/0113_complete_rafael_vega.sql
apps/dokploy/drizzle/meta/0113_snapshot.json
apps/dokploy/drizzle/meta/_journal.json
apps/dokploy/server/server.ts
packages/server/src/db/schema/deployment.ts
packages/server/src/index.ts
packages/server/src/utils/startup/cancell-deployments.ts

Please describe in a short paragraph what this PR is about.
closes #2670

2670 bug deployments are mark as running when they never ended vps shutdown

---

packages/server/src/utils/providers/bitbucket.ts

- Added support for Bitbucket email and workspace name in the authentication process.
- Updated the clone URL generation to use the correct format for API tokens.
- Improved error handling to ensure required fields are provided for both API tokens and app passwords.
- Added console logs for debugging clone URL and repository information during cloning.
Please describe in a short paragraph what this PR is about.
closes #2673

fix(bitbucket): enhance Bitbucket authentication handling
